import type { SourceRegistryEntry, TaxonomyTopic } from "./types";

/**
 * Coverage taxonomy and source registry.
 *
 * The registry is the editorial watchlist: where a development is expected to
 * surface first, what that source can and cannot establish, and how often the
 * desk intends to check it. Whether a source is actually cited in a current
 * file is computed from the content, never declared here, so the coverage page
 * can say "in use" only when it is true.
 */

export const taxonomy: TaxonomyTopic[] = [
  {
    desk: "Regulation",
    href: "/today?desk=Regulation",
    description: "Changes in what may be sold, claimed, or listed, and where.",
    includes: ["Premarket approvals and orders (sunscreen filters, drugs, devices)", "Ingredient restrictions, bans, and safety opinions", "Labeling, claims, and advertising rules", "Registration and product listing (for example MoCRA)", "Consultations and proposed rules, marked as proposals"],
  },
  {
    desk: "Safety",
    href: "/today?desk=Safety",
    description: "Actions and signals about products already on the market.",
    includes: ["Recalls and market withdrawals", "Safety communications and consumer warnings", "Adverse-event signals, marked as signals rather than rates", "Enforcement, warning letters, and counterfeit or unapproved products", "Contamination, adulteration, and undeclared ingredients"],
  },
  {
    desk: "Research",
    href: "/today?desk=Research",
    description: "Human evidence and what it can support.",
    includes: ["Randomized and controlled trials", "Systematic reviews and meta-analyses", "Observational and mechanistic studies, graded accordingly", "Trial registrations and results postings", "Funding, conflicts, and replication status"],
  },
  {
    desk: "Procedures",
    href: "/procedures",
    description: "Treatments performed on people, from spa facials to resurfacing.",
    includes: [
      "Facials and spa-grade treatments",
      "Peels and exfoliation by depth",
      "Injectables: neuromodulators, fillers, biostimulators, boosters, fat-dissolving drugs",
      "Energy devices: lasers, light, ultrasound, radiofrequency, needling, electromagnetic",
      "Body contouring, hair and scalp, and energy-based intimate devices",
      "Facial surgery families compared against their non-surgical alternatives",
      "Complication reporting, cost context, and use statistics with caveats",
    ],
  },
  {
    desk: "Topicals",
    href: "/ingredients",
    description: "Prescription, over-the-counter, and cosmetic ingredients people are actually using.",
    includes: ["U.S. status: prescription, OTC drug, or cosmetic", "Strengths and forms as sold, with generic availability", "Evidence graded per use, never per ingredient", "How to use, side effects, pregnancy and interaction cautions", "Regional rules where they differ from the U.S."],
  },
  {
    desk: "Trends",
    href: "/trends",
    description: "What people are doing, what they are told it does, and what the evidence supports.",
    includes: ["Routines (slugging, skin cycling, flooding)", "Trending ingredients and devices", "Supplements marketed for skin", "Safety verdicts, with 'Avoid' reserved for documented harm", "Where a trend touches a procedure or prescription"],
  },
  {
    desk: "Guides",
    href: "/guides",
    description: "Durable explainers written to the evidence ceiling.",
    includes: ["Routine building and barrier care", "Ingredient decisions such as retinoids", "Procedure safety checklists", "How to read a claim, a label, or a study"],
  },
  {
    desk: "Culture",
    href: "/culture",
    description: "Beauty practices in their historical and material context.",
    includes: ["Museum, archive, and scholarly sources", "Material and technological history", "Practices described without 'ancient secret' framing", "Modern claims traced back to their origins"],
  },
];

export const sourceRegistry: SourceRegistryEntry[] = [
  // ---------------------------------------------------------------- United States
  {
    id: "fda",
    name: "U.S. Food and Drug Administration",
    jurisdiction: "United States",
    region: "United States",
    type: "Regulator",
    covers: ["Recalls and safety alerts", "Device safety communications", "Cosmetic registration and listing (MoCRA)", "Sunscreen and OTC drug orders", "Drug labels and device clearances (510(k), PMA)"],
    cadence: "Daily on weekdays",
    url: "https://www.fda.gov/",
    domains: ["fda.gov", "accessdata.fda.gov"],
    note: "Primary source for U.S. regulatory status. Adverse-event databases (MAUDE, CAERS) show signals, not incidence.",
  },
  {
    id: "nih-nlm",
    name: "NIH National Library of Medicine (PubMed, DailyMed)",
    jurisdiction: "United States / international literature",
    region: "Global",
    type: "Literature",
    covers: ["Indexed trials and reviews", "Drug labeling (DailyMed)", "Author affiliations and funding statements"],
    cadence: "Weekly topic searches",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    domains: ["pubmed.ncbi.nlm.nih.gov", "ncbi.nlm.nih.gov", "dailymed.nlm.nih.gov", "nih.gov"],
    note: "Indexing is not endorsement; each paper is graded on its own design.",
  },
  {
    id: "clinicaltrials",
    name: "ClinicalTrials.gov",
    jurisdiction: "United States / international registrations",
    region: "Global",
    type: "Literature",
    covers: ["Trial registrations", "Posted results", "Sponsor and design details"],
    cadence: "Monthly for tracked interventions",
    url: "https://clinicaltrials.gov/",
    domains: ["clinicaltrials.gov"],
    note: "Used to check whether a marketed claim has a registered trial behind it.",
  },
  {
    id: "cdc",
    name: "U.S. Centers for Disease Control and Prevention",
    jurisdiction: "United States",
    region: "United States",
    type: "Public health agency",
    covers: ["Outbreak investigations linked to cosmetic procedures", "Mercury and toxic-ingredient exposure reports", "Infection-control guidance"],
    cadence: "Weekly (MMWR)",
    url: "https://www.cdc.gov/",
    domains: ["cdc.gov"],
  },
  {
    id: "ftc",
    name: "U.S. Federal Trade Commission",
    jurisdiction: "United States",
    region: "United States",
    type: "Regulator",
    covers: ["Advertising and claims enforcement", "Endorsement and review rules", "Health-claim substantiation actions"],
    cadence: "Monthly",
    url: "https://www.ftc.gov/",
    domains: ["ftc.gov"],
  },
  {
    id: "state-boards",
    name: "State medical and cosmetology boards",
    jurisdiction: "United States, state level",
    region: "United States",
    type: "Regulator",
    covers: ["Scope of practice for estheticians, nurses, and delegation", "Laser and device operator rules", "Disciplinary actions"],
    cadence: "As needed per procedure file",
    url: "https://www.fda.gov/medical-devices/products-and-medical-procedures/aesthetic-cosmetic-devices",
    domains: [],
    note: "No single national source; rules differ by state. Procedure files say when a rule varies rather than pretending one answer exists.",
  },
  {
    id: "aad",
    name: "American Academy of Dermatology",
    jurisdiction: "United States",
    region: "United States",
    type: "Professional society",
    covers: ["Patient education on treatments and conditions", "Clinical guidelines", "Position statements"],
    cadence: "Monthly",
    url: "https://www.aad.org/",
    domains: ["aad.org"],
  },
  {
    id: "asds",
    name: "American Society for Dermatologic Surgery",
    jurisdiction: "United States",
    region: "United States",
    type: "Professional society",
    covers: ["Procedure explainers", "Consumer surveys", "Safety positions on delegation"],
    cadence: "Monthly",
    url: "https://www.asds.net/",
    domains: ["asds.net"],
  },
  {
    id: "asps",
    name: "American Society of Plastic Surgeons",
    jurisdiction: "United States",
    region: "United States",
    type: "Statistics",
    covers: ["Annual procedural statistics", "Average physician fees on procedure pages", "Procedure descriptions"],
    cadence: "Annually, plus cost pages quarterly",
    url: "https://www.plasticsurgery.org/",
    domains: ["plasticsurgery.org"],
    note: "Its 2025 report stopped publishing minimally invasive counts and fees; older figures are labeled as such.",
  },

  // ---------------------------------------------------------------- Global and other jurisdictions
  {
    id: "isaps",
    name: "International Society of Aesthetic Plastic Surgery",
    jurisdiction: "Global",
    region: "Global",
    type: "Statistics",
    covers: ["Annual global survey of aesthetic procedures", "Country rankings and settings"],
    cadence: "Annually",
    url: "https://www.isaps.org/discover/about-isaps/global-statistics/",
    domains: ["isaps.org"],
    note: "Survey of plastic surgeons; excludes dermatology and non-physician settings, so counts understate spa-based procedures.",
  },
  {
    id: "who",
    name: "World Health Organization",
    jurisdiction: "Global",
    region: "Global",
    type: "Public health agency",
    covers: ["Mercury in skin-lightening products", "Substandard and falsified product alerts"],
    cadence: "Monthly",
    url: "https://www.who.int/",
    domains: ["who.int"],
  },
  {
    id: "cochrane",
    name: "Cochrane Library",
    jurisdiction: "Global",
    region: "Global",
    type: "Literature",
    covers: ["Systematic reviews of interventions", "Evidence certainty assessments"],
    cadence: "Monthly for tracked topics",
    url: "https://www.cochranelibrary.com/",
    domains: ["cochranelibrary.com"],
  },
  {
    id: "eu-safety-gate",
    name: "European Commission Safety Gate",
    jurisdiction: "European Union",
    region: "Europe",
    type: "Regulator",
    covers: ["Weekly alerts on dangerous consumer products, including cosmetics", "Ingredient-driven recalls across member states"],
    cadence: "Weekly",
    url: "https://ec.europa.eu/safety-gate-alerts/screen/webReport",
    domains: ["ec.europa.eu"],
  },
  {
    id: "sccs",
    name: "Scientific Committee on Consumer Safety (SCCS)",
    jurisdiction: "European Union",
    region: "Europe",
    type: "Regulator",
    covers: ["Ingredient safety opinions", "Concentration limits behind Annex changes"],
    cadence: "Monthly",
    url: "https://health.ec.europa.eu/scientific-committees/scientific-committee-consumer-safety-sccs_en",
    domains: ["health.ec.europa.eu"],
  },
  {
    id: "ema",
    name: "European Medicines Agency",
    jurisdiction: "European Union",
    region: "Europe",
    type: "Regulator",
    covers: ["Botulinum toxin and other prescription aesthetic drugs", "Safety referrals"],
    cadence: "Monthly",
    url: "https://www.ema.europa.eu/en",
    domains: ["ema.europa.eu"],
  },
  {
    id: "uk-opss-mhra",
    name: "U.K. Office for Product Safety and Standards / MHRA",
    jurisdiction: "United Kingdom",
    region: "Europe",
    type: "Regulator",
    covers: ["Product recalls and safety notices", "Cosmetics notification data", "Medicines and device alerts"],
    cadence: "Weekly",
    url: "https://www.gov.uk/government/organisations/office-for-product-safety-and-standards",
    domains: ["gov.uk"],
  },
  {
    id: "nhs",
    name: "NHS cosmetic procedures guidance",
    jurisdiction: "United Kingdom",
    region: "Europe",
    type: "Public health agency",
    covers: ["Plain-language procedure guidance", "Practitioner and complication advice"],
    cadence: "Quarterly",
    url: "https://www.nhs.uk/conditions/cosmetic-procedures/",
    domains: ["nhs.uk"],
  },
  {
    id: "health-canada",
    name: "Health Canada",
    jurisdiction: "Canada",
    region: "United States",
    type: "Regulator",
    covers: ["Recalls and safety alerts", "Cosmetic ingredient hotlist", "Device licensing"],
    cadence: "Weekly",
    url: "https://www.canada.ca/en/health-canada.html",
    domains: ["canada.ca"],
    note: "Grouped with North America on the wire.",
  },
  {
    id: "tga",
    name: "Therapeutic Goods Administration",
    jurisdiction: "Australia",
    region: "Oceania",
    type: "Regulator",
    covers: ["Sunscreen regulation and testing", "Recalls", "Device and medicine alerts"],
    cadence: "Weekly",
    url: "https://www.tga.gov.au/",
    domains: ["tga.gov.au"],
  },
  {
    id: "anvisa",
    name: "ANVISA",
    jurisdiction: "Brazil",
    region: "Latin America",
    type: "Regulator",
    covers: ["Recalls and resolutions", "Cosmetic and sunscreen registration"],
    cadence: "Weekly",
    url: "https://www.gov.br/anvisa/pt-br",
    domains: ["gov.br"],
  },
  {
    id: "pmda",
    name: "Japan PMDA / MHLW",
    jurisdiction: "Japan",
    region: "Asia",
    type: "Regulator",
    covers: ["Quasi-drug approvals", "Safety information"],
    cadence: "Monthly",
    url: "https://www.pmda.go.jp/english/",
    domains: ["pmda.go.jp", "mhlw.go.jp"],
  },
  {
    id: "mfds",
    name: "South Korea MFDS",
    jurisdiction: "South Korea",
    region: "Asia",
    type: "Regulator",
    covers: ["Functional cosmetics rules", "Device and injectable approvals", "Recalls"],
    cadence: "Monthly",
    url: "https://www.mfds.go.kr/eng/index.do",
    domains: ["mfds.go.kr"],
  },
  {
    id: "nmpa",
    name: "China NMPA",
    jurisdiction: "China",
    region: "Asia",
    type: "Regulator",
    covers: ["Cosmetic registration and filing", "Ingredient rules", "Enforcement"],
    cadence: "Monthly",
    url: "https://www.nmpa.gov.cn/",
    domains: ["nmpa.gov.cn"],
  },
  {
    id: "cdsco",
    name: "India CDSCO",
    jurisdiction: "India",
    region: "Asia",
    type: "Regulator",
    covers: ["Cosmetic rules and import registration", "Alerts"],
    cadence: "Monthly",
    url: "https://cdsco.gov.in/opencms/opencms/en/Home/",
    domains: ["cdsco.gov.in"],
  },
  {
    id: "archives",
    name: "Museums, archives, and scholarly repositories",
    jurisdiction: "Global",
    region: "Global",
    type: "Archive",
    covers: ["Object records and collection notes", "Peer-reviewed history and anthropology", "Accountable community and institutional sources"],
    cadence: "Per culture file",
    url: "https://www.metmuseum.org/",
    domains: ["metmuseum.org", "museoegizio.it", "cir.nii.ac.jp", "insa.nic.in", "visitmorocco.com", "britishmuseum.org", "jstor.org"],
  },
];
