import type { Ingredient } from "./types";

export const ingredients: Ingredient[] = [
  {
    slug: "retinoids",
    aliases: ["retinoid", "retinol", "retinaldehyde", "tretinoin", "adapalene"],
    name: "Retinoids",
    family: "Vitamin A derivatives",
    evidence: "A",
    jobs: ["Acne", "Photoaging", "Uneven tone"],
    watchFor: "Dryness, irritation, pregnancy precautions, and molecule-specific rules.",
    summary: "A broad family with substantial evidence—but very different members, strengths, and regulatory status.",
    guideSlug: "retinoid-ladder",
  },
  {
    slug: "niacinamide",
    aliases: ["vitamin b3", "nicotinamide"],
    name: "Niacinamide",
    family: "Vitamin B3 derivative",
    evidence: "B",
    jobs: ["Barrier support", "Uneven tone", "Redness"],
    watchFor: "Higher percentages are not automatically more effective and may be less tolerable.",
    summary: "A versatile topical with useful human evidence, often strongest as part of a well-built formula rather than a percentage contest.",
  },
  {
    slug: "ceramides",
    aliases: ["ceramide", "barrier lipids"],
    name: "Ceramides",
    family: "Barrier lipids",
    evidence: "B",
    jobs: ["Dryness", "Barrier support", "Sensitive-skin routines"],
    watchFor: "The ratio, delivery system, and full moisturizer base matter more than the word on the label.",
    summary: "Skin-identical lipid families used in emollients; evidence belongs to specific formulations and populations.",
  },
  {
    slug: "azelaic-acid",
    aliases: ["azelaic"],
    name: "Azelaic acid",
    family: "Dicarboxylic acid",
    evidence: "A",
    jobs: ["Acne", "Uneven tone", "Rosacea care"],
    watchFor: "Stinging and dryness; drug/cosmetic status and strengths vary by market.",
    summary: "A well-established multitasker with prescription and nonprescription forms depending on location.",
  },
  {
    slug: "vitamin-c",
    aliases: ["ascorbic acid", "ascorbate"],
    name: "Vitamin C",
    family: "Antioxidants",
    evidence: "B",
    jobs: ["Antioxidant support", "Uneven tone", "Photoaging"],
    watchFor: "Stability, packaging, derivative, pH, and oxidation make cross-product comparisons difficult.",
    summary: "Promising and formulation-sensitive; ‘contains vitamin C’ says far less than most labels imply.",
  },
  {
    slug: "bemotrizinol",
    aliases: ["bis-ethylhexyloxyphenol methoxyphenyl triazine"],
    name: "Bemotrizinol",
    family: "Organic UV filters",
    evidence: "A",
    jobs: ["Broad-spectrum UV protection", "Formula photostability"],
    watchFor: "Availability and permitted concentration differ by market; judge the finished sunscreen.",
    summary: "A photostable UVA/UVB filter long used outside the U.S. and added to the U.S. OTC monograph in June 2026.",
  },
  {
    slug: "ectoin",
    aliases: ["ectoine"],
    name: "Ectoin",
    family: "Extremolytes",
    evidence: "C",
    jobs: ["Hydration", "Barrier support", "Irritation-focused formulas"],
    watchFor: "A growing ingredient story with a smaller independent clinical base than the marketing footprint suggests.",
    summary: "Biologically interesting and increasingly popular, but finished-formula claims need study-by-study scrutiny.",
  },
];
