import type { Ingredient, Source } from "./types";

/**
 * Topical files: what people are actually buying, prescribing, and posting
 * about. Each file separates U.S. market status (prescription, OTC drug,
 * cosmetic), the forms sold, evidence graded per use, how to use it, side
 * effects, cautions, access, and where it appears in current trends.
 *
 * Grades belong to the specific use. A retinoid's acne grade says nothing
 * about a peptide's wrinkle claim, and a cosmetic concentration is not the
 * prescription product it borrows a name from.
 */

const REVIEWED = "2026-09-01";

const dailymed = (query: string, label: string): Source => ({
  label: `NIH DailyMed — ${label} labels`,
  url: `https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=${encodeURIComponent(query)}`,
});

const src = {
  aadAcneGuideline: { label: "American Academy of Dermatology — 2024 acne guideline", url: "https://www.aad.org/member/clinical-quality/guidelines/acne" },
  aadAcneGuidelinePm: { label: "J Am Acad Dermatol 2024 — guidelines of care for the management of acne vulgaris (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/38300170/" },
  aadRetinoids: { label: "American Academy of Dermatology — retinoid or retinol?", url: "https://www.aad.org/public/everyday-care/skin-care-secrets/anti-aging/retinoid-retinol" },
  aadAdultAcne: { label: "American Academy of Dermatology — adult acne treatment", url: "https://www.aad.org/public/diseases/acne/diy/adult-acne-treatment" },
  aadAcneWontClear: { label: "American Academy of Dermatology — when acne won't clear", url: "https://www.aad.org/public/diseases/acne/diy/wont-clear" },
  aadMelasma: { label: "American Academy of Dermatology — melasma treatment", url: "https://www.aad.org/public/diseases/a-z/melasma-treatment" },
  aadRosacea: { label: "American Academy of Dermatology — rosacea treatment", url: "https://www.aad.org/public/diseases/rosacea/treatment" },
  aadVitiligo: { label: "American Academy of Dermatology — vitiligo treatment", url: "https://www.aad.org/public/diseases/a-z/vitiligo-treatment" },
  aadAdGuideline: { label: "American Academy of Dermatology — atopic dermatitis guidelines", url: "https://www.aad.org/member/clinical-quality/guidelines/atopic-dermatitis" },
  aadDrySkin: { label: "American Academy of Dermatology — tips to relieve dry skin", url: "https://www.aad.org/public/everyday-care/skin-care-basics/dry/dermatologists-tips-relieve-dry-skin" },
  aadPetroleum: { label: "American Academy of Dermatology — uses for petroleum jelly", url: "https://www.aad.org/public/everyday-care/skin-care-secrets/routine/petroleum-jelly" },
  aadSunscreenFaq: { label: "American Academy of Dermatology — sunscreen FAQs", url: "https://www.aad.org/public/everyday-care/sun-protection/sunscreen-patients/sunscreen-faqs" },
  aadSunscreenSelect: { label: "American Academy of Dermatology — how to select a sunscreen", url: "https://www.aad.org/public/everyday-care/sun-protection/shade-clothing-sunscreen/how-to-select-sunscreen" },
  aadHairLoss: { label: "American Academy of Dermatology — hair loss treatment options", url: "https://www.aad.org/public/diseases/hair-loss/treatment" },
  aadOrder: { label: "American Academy of Dermatology — applying skin care products in order", url: "https://www.aad.org/public/everyday-care/skin-care-basics/care/apply-skin-care-certain-order" },
  fdaSkinLightening: { label: "U.S. FDA — protecting consumers from potentially harmful OTC skin lightening products", url: "https://www.fda.gov/drugs/drug-safety-communications/fda-works-protect-consumers-potentially-harmful-otc-skin-lightening-products" },
  fdaSkinFacts: { label: "U.S. FDA — Skin Facts: what you need to know about skin lightening products", url: "https://www.fda.gov/consumers/health-fraud-scams/skin-facts-what-you-need-know-about-skin-lightening-products" },
  fdaBenzene: { label: "U.S. FDA — results of testing acne products for benzene (2025)", url: "https://www.fda.gov/drugs/drug-alerts-and-statements/limited-number-voluntary-recalls-initiated-after-fda-testing-acne-products-benzene-findings-show", published: "March 2025" },
  fdaBpoMonograph: { label: "U.S. FDA — OTC topical acne drug products: benzoyl peroxide classification", url: "https://www.fda.gov/regulatory-information/search-fda-guidance-documents/topical-acne-drug-products-over-counter-human-use-revision-labeling-and-classification-benzoyl" },
  fdaSunscreen: { label: "U.S. FDA — sunscreen: how to help protect your skin from the sun", url: "https://www.fda.gov/drugs/understanding-over-counter-medicines/sunscreen-how-help-protect-your-skin-sun" },
  fdaSunscreenRulemaking: { label: "U.S. FDA — rulemaking history for OTC sunscreen drug products", url: "https://www.fda.gov/drugs/status-otc-rulemakings/rulemaking-history-otc-sunscreen-drug-products" },
  fdaAha: { label: "U.S. FDA — alpha hydroxy acids in cosmetics", url: "https://www.fda.gov/cosmetics/cosmetic-ingredients/alpha-hydroxy-acids" },
  fdaBha: { label: "U.S. FDA — beta hydroxy acids in cosmetics", url: "https://www.fda.gov/cosmetics/cosmetic-ingredients/beta-hydroxy-acids" },
  fdaWrinkle: { label: "U.S. FDA — wrinkle treatments and other anti-aging products", url: "https://www.fda.gov/cosmetics/cosmetic-products/wrinkle-treatments-and-other-anti-aging-products" },
  fdaCosmeticsAuthority: { label: "U.S. FDA — how cosmetics are regulated (not FDA approved)", url: "https://www.fda.gov/cosmetics/cosmetics-laws-regulations/fda-authority-over-cosmetics-how-cosmetics-are-not-fda-approved-are-fda-regulated" },
  pmCochraneAcne: { label: "Cochrane 2020 — topical azelaic acid, salicylic acid, nicotinamide, sulphur, zinc and fruit acid for acne (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/32356369/" },
  pmAcneNma: { label: "Br J Dermatol 2022 — network meta-analysis of acne treatments (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/35789996/" },
  pmAzelaicSr: { label: "J Cosmet Dermatol 2023 — azelaic acid in acne, rosacea, melasma and aging: systematic review (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/37550898/" },
  pmRosaceaNma: { label: "JAAD Int 2025 — minocycline, metronidazole, ivermectin, and azelaic acid in papulopustular rosacea: network meta-analysis (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/40213532/" },
  pmRosaceaTopicalNma: { label: "JAMA Dermatol 2026 — topical preparations for moderate to severe rosacea: network meta-analysis (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/42384418/" },
  pmTazVsTret: { label: "J Am Acad Dermatol 2000 — tazarotene versus tretinoin or adapalene in acne (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/10898831/" },
  pmTazVsTret2: { label: "Cutis 2001 — tazarotene 0.1% gel versus tretinoin 0.025% gel in facial acne: randomized trial (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/11499329/" },
  pmTazPhoto: { label: "J Am Acad Dermatol 2005 — tazarotene 0.1% cream for photodamage: randomized trial (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/15692472/" },
  pmTazPhoto2: { label: "Arch Dermatol 2001 — tazarotene creams versus tretinoin 0.05% for facial photodamage (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/11735710/" },
  pmRetinoidPregnancy: { label: "Front Drug Saf Regul 2026 — topical retinoids and congenital malformations: meta-analysis (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/42564875/" },
  pmBakuchiol: { label: "Br J Dermatol 2019 — bakuchiol versus retinol for photoaging: randomized double-blind trial (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/29947134/" },
  pmBenzene: { label: "J Invest Dermatol 2025 — benzene presence and formation in benzoyl peroxide products (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/39384016/" },
  pmClascoterone: { label: "JAMA Dermatol 2020 — clascoterone cream 1% for facial acne: two phase 3 RCTs (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/32320027/" },
  pmOchronosis: { label: "Int J Dermatol 2022 — exogenous ochronosis associated with hydroquinone: systematic review (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/34486734/" },
  pmTxaMa: { label: "J Dermatolog Treat 2024 — tranexamic acid for melasma: meta-analysis of RCTs (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/38843906/" },
  pmMelasmaNma: { label: "Front Med 2021 — melasma treatments: network meta-analysis of RCTs (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/34660626/" },
  pmVitC: { label: "J Cosmet Dermatol 2023 — topical vitamin C in melasma and photoaging: systematic review (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/37128827/" },
  pmNiacinamide: { label: "Antioxidants 2021 — niacinamide for skin aging and pigmentation: mechanisms and clinical evidence (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/34439563/" },
  pmNiacinamide2: { label: "Skin Pharmacol Physiol 2014 — niacinamide mechanisms and topical use (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/24993939/" },
  pmDelphi: { label: "J Am Acad Dermatol 2025 — skincare ingredients recommended by cosmetic dermatologists: Delphi consensus (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/40233838/" },
  pmCeramideBjd: { label: "Br J Dermatol 2025 — physiological lipid supplementation rebalances stratum corneum ceramides (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/40408261/" },
  pmHaReview: { label: "Dermatol Ther 2022 — topical hyaluronic acid for skin quality and aging: review and clinical evidence (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/36200921/" },
  pmHaXerosis: { label: "Arch Dermatol Res 2024 — topical hyaluronic acid of different molecular weights in xerosis: double-blind RCT (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/38829483/" },
  pmPetrolatum: { label: "J Allergy Clin Immunol 2016 — petrolatum: barrier repair and antimicrobial responses (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/26431582/" },
  pmUrea: { label: "Diabet Med 2017 — moisturizer for xerosis and cracks of the feet in diabetes: randomized placebo-controlled study (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/28627029/" },
  pmSunscreenMelanoma: { label: "J Clin Oncol 2011 — reduced melanoma after regular sunscreen use: randomized trial follow-up (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/21135266/" },
  pmSunscreenAging: { label: "Ann Intern Med 2013 — sunscreen and prevention of skin aging: randomized trial (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/23732711/" },
  pmCosmeceuticals: { label: "Arch Dermatol Res 2024 — cosmeceuticals for anti-aging: systematic review of safety and efficacy (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/38758222/" },
  pmCopper: { label: "Arch Facial Plast Surg 2006 — topical copper tripeptide complex on laser-resurfaced skin (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/16847171/" },
  pmGrowthFactors: { label: "J Cosmet Dermatol 2023 — topical growth factor preparations for facial rejuvenation: systematic review (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/37222303/" },
  pmRuxo: { label: "N Engl J Med 2022 — two phase 3 trials of ruxolitinib cream for vitiligo (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/36260792/" },
} satisfies Record<string, Source>;

export const ingredients: Ingredient[] = [
  // ------------------------------------------------------------------
  // Retinoids
  // ------------------------------------------------------------------
  {
    slug: "retinoids",
    name: "Retinoids (the family)",
    family: "Vitamin A derivatives",
    evidence: "A",
    jobs: ["Acne", "Photoaging and fine lines", "Texture and tone", "Post-acne marks"],
    watchFor: "Dryness, peeling, and irritation in the first weeks; sun sensitivity; avoid in pregnancy. Strength on the label does not equal potency across molecules.",
    summary: "The best-evidenced topical family for acne and photoaging. Prescription retinoids (tretinoin, tazarotene, adapalene 0.3%) are drugs; retinol and retinal are cosmetics that convert in skin and act more slowly.",
    guideSlug: "retinoid-ladder",
    aliases: ["retinol", "retinal", "retinaldehyde", "tretinoin", "adapalene", "tazarotene", "trifarotene", "vitamin A"],
    status: "Prescription or cosmetic (U.S.)",
    forms: ["Cosmetic: retinol 0.1–1%, retinaldehyde 0.05–0.1%, retinyl esters", "OTC drug: adapalene 0.1% gel", "Prescription: tretinoin, adapalene 0.3%, tazarotene, trifarotene"],
    uses: [
      { use: "Acne", grade: "A", note: "Topical retinoids are first-line in the 2024 AAD guideline, alone or with benzoyl peroxide." },
      { use: "Photoaging, fine lines, pigment", grade: "A", note: "Prescription tretinoin and tazarotene have randomized trial evidence; retinol has smaller trials with slower, milder effects." },
      { use: "Post-inflammatory marks and texture", grade: "B", note: "Supported by acne trial secondary outcomes and pigment studies." },
    ],
    howToUse: "Pea-sized amount at night on dry skin, starting 2–3 nights a week and building to nightly as tolerated. Moisturize and use sunscreen daily. Expect 8–12 weeks for acne and 3–6 months for photoaging.",
    sideEffects: ["Dryness, redness, and peeling (retinization)", "Stinging with other actives", "Increased sun sensitivity"],
    cautions: "Avoid in pregnancy and while trying to conceive as a precaution; do not combine with benzoyl peroxide in the same application unless the product is formulated for it; separate from strong acids while adjusting.",
    access: "Tretinoin and adapalene are inexpensive generics; adapalene 0.1% is OTC. Tazarotene has generics. Retinol pricing tracks the brand, not the evidence.",
    regulatory: "Prescription retinoids are FDA-approved drugs for acne (and some for photodamage); adapalene 0.1% moved OTC in 2016. Retinol and retinal are cosmetic ingredients with no premarket review. In the E.U., cosmetic retinol is being capped at 0.3% face / 0.05% body under a phased rule.",
    trendNote: "Retinol sandwiching, skin cycling, and bakuchiol-as-retinol all live in the trends desk.",
    reviewed: REVIEWED,
    sources: [src.aadAcneGuideline, src.aadAcneGuidelinePm, src.aadRetinoids, src.pmRetinoidPregnancy],
    related: { guides: ["retinoid-ladder"], ingredients: ["tretinoin", "tazarotene", "adapalene", "retinol-retinal"], trends: ["skin-cycling", "retinol-sandwiching"] },
  },
  {
    slug: "tretinoin",
    name: "Tretinoin",
    family: "Vitamin A derivatives",
    evidence: "A",
    jobs: ["Acne", "Photoaging", "Fine wrinkles", "Mottled pigmentation"],
    watchFor: "The first 4–8 weeks are the hardest; most people who quit do so then. Gel and higher strengths irritate more than cream at the same percentage.",
    summary: "The reference retinoid: decades of randomized trials for acne and photodamage, cheap as a generic, and the benchmark every newer molecule is measured against.",
    aliases: ["Retin-A", "retinoic acid", "Altreno", "Renova", "all-trans retinoic acid"],
    status: "Prescription (U.S.)",
    forms: ["0.025%, 0.05%, 0.1% cream and gel (Rx, generic)", "0.05% lotion (Rx)", "0.02% cream approved for fine wrinkles (Rx)", "Fixed combinations with clindamycin or benzoyl peroxide (Rx)"],
    uses: [
      { use: "Acne", grade: "A", note: "First-line in guidelines, with the largest trial base of any topical retinoid." },
      { use: "Photoaging and fine wrinkles", grade: "A", note: "Vehicle-controlled trials of 0.02–0.05% cream show improvement over 24–48 weeks; the 0.02% cream carries an FDA indication for fine facial wrinkles." },
      { use: "Melasma and dark spots", grade: "B", note: "Effective alone and as part of triple-combination therapy; slower than hydroquinone." },
    ],
    howToUse: "Pea-sized amount to the whole face at night, 20–30 minutes after washing, starting 2–3 nights a week. Increase strength only after months of tolerance; more is not faster.",
    sideEffects: ["Redness, peeling, and dryness", "Temporary acne flare in the first weeks", "Photosensitivity"],
    cautions: "Not recommended in pregnancy; a 2026 meta-analysis of topical retinoids found no clear malformation signal, but guidance remains precautionary. Avoid waxing and aggressive peels on treated skin. Eczema and rosacea can flare.",
    access: "Generic creams and gels are among the cheapest prescription skincare products. Brand lotions and combination products cost far more; ask for the generic if cost matters. Telehealth prescriptions are common.",
    regulatory: "FDA-approved prescription drug for acne; 0.02% cream approved as an adjunct for fine wrinkles and pigmentation. Prescription-only in the U.S., U.K., E.U., and Canada; some countries sell it over the counter.",
    trendNote: "Tretinoin 'purging' videos and DIY compounding are the trend edge; neither changes the dosing above.",
    reviewed: REVIEWED,
    sources: [dailymed("tretinoin", "tretinoin"), src.aadAcneGuideline, src.aadRetinoids, src.pmRetinoidPregnancy],
    related: { guides: ["retinoid-ladder"], ingredients: ["retinoids", "tazarotene", "adapalene"] },
  },
  {
    slug: "tazarotene",
    name: "Tazarotene",
    family: "Vitamin A derivatives",
    evidence: "A",
    jobs: ["Acne", "Photodamage", "Psoriasis plaques", "Fine wrinkles and mottled pigmentation"],
    watchFor: "The most irritating retinoid at equal strength; the 0.045% lotion was designed to soften that. Contraindicated in pregnancy, not just discouraged.",
    summary: "The strongest topical retinoid, with randomized trials showing acne results at least equal to tretinoin and a rare FDA indication for photodamage. Irritation is the price.",
    aliases: ["Tazorac", "Arazlo", "Avage", "Fabior", "tazarotene cream", "tazarotene gel", "tazarotene lotion"],
    status: "Prescription (U.S.)",
    forms: ["0.045% lotion (Rx)", "0.05% and 0.1% cream and gel (Rx, generic)", "0.1% foam (Rx)"],
    uses: [
      { use: "Acne", grade: "A", note: "Randomized trials found tazarotene 0.1% gel at least as effective as tretinoin, with more irritation in some comparisons; the 0.045% lotion trades some potency for tolerability." },
      { use: "Photodamage (fine wrinkles, mottled pigmentation, roughness)", grade: "A", note: "Multicenter 24-week and 12-month randomized trials of 0.1% cream showed improvement versus vehicle, comparable to tretinoin 0.05%; the cream carries an FDA indication." },
      { use: "Plaque psoriasis", grade: "A", note: "FDA-approved indication, usually combined with a topical steroid." },
    ],
    howToUse: "Thin layer at night on dry skin, starting every other night; many people need a moisturizer buffer for the first month. Short-contact application (rinse after 20–60 minutes) is a recognized tolerability strategy.",
    sideEffects: ["Burning, stinging, and peeling", "Dryness and redness", "Photosensitivity"],
    cautions: "Contraindicated in pregnancy; the label advises a pregnancy test before starting in people who can become pregnant. Avoid on eczematous skin and with other drying agents until tolerated.",
    access: "Generic 0.05% and 0.1% cream and gel are available; the lotion and foam are brand-only and costly. Insurance often requires a tretinoin trial first.",
    regulatory: "FDA-approved prescription drug for acne, psoriasis, and (0.1% cream) facial photodamage. Prescription-only in the U.S., U.K., E.U., and Canada.",
    trendNote: "Tazarotene is having a moment on social media as the 'strongest retinoid'; strength without tolerance produces quitting, not results.",
    reviewed: REVIEWED,
    sources: [dailymed("tazarotene", "tazarotene"), src.pmTazVsTret, src.pmTazVsTret2, src.pmTazPhoto, src.pmTazPhoto2, src.aadAcneGuideline],
    related: { guides: ["retinoid-ladder"], ingredients: ["retinoids", "tretinoin", "adapalene"] },
  },
  {
    slug: "adapalene",
    name: "Adapalene",
    family: "Vitamin A derivatives",
    evidence: "A",
    jobs: ["Acne", "Comedones", "Post-acne marks"],
    watchFor: "Cheapest way into a real retinoid. The OTC 0.1% gel works; the 0.3% is prescription. Pairs well with benzoyl peroxide because it is chemically stable with it.",
    summary: "A gentler, light-stable retinoid that became the first OTC retinoid drug in the U.S. Best evidence is for acne; photoaging data are thinner than for tretinoin.",
    aliases: ["Differin", "Epiduo", "adapalene gel", "OTC retinoid"],
    status: "OTC drug or prescription (U.S.)",
    forms: ["0.1% gel (OTC drug)", "0.1% cream and lotion, 0.3% gel (Rx)", "Adapalene/benzoyl peroxide 0.1%/2.5% and 0.3%/2.5% (Rx)"],
    uses: [
      { use: "Acne", grade: "A", note: "Guideline first-line; fixed-dose adapalene/benzoyl peroxide has strong trial support for inflammatory acne." },
      { use: "Post-inflammatory marks", grade: "B", note: "Improvement tracks acne control; some trials measured pigment secondary outcomes." },
      { use: "Photoaging", grade: "C", note: "Small studies only; tretinoin and tazarotene carry the indication." },
    ],
    howToUse: "Thin layer once daily at night to the whole acne-prone area, not spot treatment. Results at 8–12 weeks; keep going to prevent new lesions.",
    sideEffects: ["Dryness and mild peeling", "Redness in the first weeks", "Sun sensitivity"],
    cautions: "AAD advises avoiding topical retinoids in pregnancy as a precaution even though adapalene absorption is low. Stop before waxing.",
    access: "OTC 0.1% gel is inexpensive and widely stocked; prescription 0.3% and combination gels cost more and are often generic.",
    regulatory: "0.1% gel is an FDA-approved OTC drug (switched in 2016); higher strengths and combinations are prescription. Prescription-only in most other countries.",
    trendNote: "Often recommended in 'skinimalism' routines as the one active worth keeping.",
    reviewed: REVIEWED,
    sources: [dailymed("adapalene", "adapalene"), src.aadAcneGuideline, src.aadAcneGuidelinePm, src.aadRetinoids],
    related: { guides: ["retinoid-ladder"], ingredients: ["retinoids", "benzoyl-peroxide", "tretinoin"] },
  },
  {
    slug: "retinol-retinal",
    name: "Retinol and retinaldehyde",
    family: "Vitamin A derivatives",
    evidence: "B",
    jobs: ["Fine lines", "Texture", "Mild acne-prone skin", "Uneven tone"],
    watchFor: "Cosmetic percentages are not comparable across brands, and encapsulated or unstable products can deliver much less than the label suggests. Retinal is closer to the active form and tends to work faster.",
    summary: "The over-the-counter cousins: real but slower and milder than prescription retinoids, with evidence mostly from small vehicle-controlled cosmetic trials.",
    aliases: ["retinol", "retinal", "retinaldehyde", "retinyl palmitate", "retinyl retinoate", "granactive retinoid", "bakuchiol"],
    status: "Cosmetic ingredient",
    forms: ["Retinol 0.1–1% serums and creams", "Retinaldehyde 0.05–0.1%", "Retinyl esters (weakest)", "Retinoid alternatives marketed as bakuchiol"],
    uses: [
      { use: "Fine lines and photoaging", grade: "B", note: "Small randomized trials show improvement over 12–24 weeks; effect sizes are smaller than prescription tretinoin. A 2019 trial found bakuchiol comparable to retinol 0.5% with less irritation." },
      { use: "Mild acne and congestion", grade: "C", note: "Plausible via the same pathway; controlled acne trials are scarce." },
      { use: "Pigment", grade: "C", note: "Modest effects in cosmetic studies." },
    ],
    howToUse: "Start low (0.2–0.3% retinol or 0.05% retinal) a few nights a week and build. Keep products in opaque, airless packaging; exposure to air and light degrades them.",
    sideEffects: ["Dryness and flaking", "Redness", "Sun sensitivity"],
    cautions: "Avoid in pregnancy as a precaution. Combining with prescription retinoids adds irritation without adding benefit.",
    access: "Wide price range with no relationship to evidence. Formulation stability matters more than brand.",
    regulatory: "Cosmetic ingredients in the U.S. with no premarket review of claims or concentration. The E.U. is phasing in a 0.3% face cap; Canada and others restrict claims.",
    trendNote: "Retinol sandwiching and skin cycling are the routines; bakuchiol is the 'natural retinol' pitch.",
    reviewed: REVIEWED,
    sources: [src.aadRetinoids, src.pmBakuchiol, src.pmCosmeceuticals, src.fdaWrinkle],
    related: { guides: ["retinoid-ladder"], ingredients: ["retinoids", "adapalene"], trends: ["retinol-sandwiching", "skin-cycling"] },
  },

  // ------------------------------------------------------------------
  // Acne actives
  // ------------------------------------------------------------------
  {
    slug: "benzoyl-peroxide",
    name: "Benzoyl peroxide",
    family: "Antimicrobial acne actives",
    evidence: "A",
    jobs: ["Inflammatory acne", "Preventing antibiotic resistance", "Body acne"],
    watchFor: "Bleaches towels and pillowcases. 2.5% works about as well as 10% with less irritation. Store cool: heat drives benzene formation in some products.",
    summary: "The workhorse antimicrobial for acne, over the counter and cheap, and the reason topical antibiotics should never be used alone.",
    aliases: ["BPO", "benzoyl peroxide wash", "PanOxyl", "Epiduo", "benzoyl peroxide gel"],
    status: "OTC drug or prescription (U.S.)",
    forms: ["2.5–10% washes, gels, and creams (OTC drug)", "Fixed combinations with adapalene, clindamycin, or tretinoin (Rx)"],
    uses: [
      { use: "Inflammatory acne", grade: "A", note: "Guideline-recommended alone and in combinations; kills acne bacteria without resistance." },
      { use: "With topical antibiotics", grade: "A", note: "Reduces resistance; guidelines advise never using clindamycin without it." },
      { use: "Body acne", grade: "B", note: "Washes at 5–10% are practical for chest and back." },
    ],
    howToUse: "Start with 2.5–5% once daily; washes can be left on for 1–2 minutes before rinsing. Use white towels. Apply retinoid and benzoyl peroxide at different times unless the product is formulated together.",
    sideEffects: ["Dryness and peeling", "Redness and stinging", "Rare allergic contact dermatitis"],
    cautions: "Can inactivate tretinoin if layered together (adapalene is stable with it). Keep away from hair and colored fabric. Discard old or heat-exposed products.",
    access: "Inexpensive OTC; store brands are equivalent. Prescription combinations cost more.",
    regulatory: "OTC drug under FDA's acne monograph at 2.5–10%. In March 2025 FDA reported that more than 90% of tested products had undetectable or very low benzene and recommended a limited number of retail recalls; heat and age raise benzene, so storage matters.",
    trendNote: "The 2024–2025 benzene scare drove a wave of 'throw out your BPO' content; FDA's own testing found the problem concentrated in a few products.",
    reviewed: REVIEWED,
    sources: [src.fdaBpoMonograph, src.fdaBenzene, src.pmBenzene, src.aadAcneGuideline, dailymed("benzoyl peroxide", "benzoyl peroxide")],
    related: { ingredients: ["adapalene", "clindamycin-topical", "salicylic-acid"] },
  },
  {
    slug: "salicylic-acid",
    name: "Salicylic acid",
    family: "Hydroxy acids",
    evidence: "B",
    jobs: ["Blackheads and congestion", "Mild acne", "Oily skin", "Keratosis pilaris"],
    watchFor: "Modest on its own. Cochrane found low-quality evidence for acne; it shines as a maintenance cleanser or for comedones, not for inflamed cysts.",
    summary: "The oil-soluble exfoliant that reaches into pores. Useful and gentle at 0.5–2%; over-marketed as an acne cure.",
    aliases: ["BHA", "beta hydroxy acid", "salicylic acid cleanser", "2% BHA"],
    status: "OTC drug or prescription (U.S.)",
    forms: ["0.5–2% cleansers, toners, and leave-ons (OTC drug for acne)", "Higher strengths in peels and wart products (Rx or professional)"],
    uses: [
      { use: "Comedonal and mild acne", grade: "B", note: "Cochrane 2020 rated the evidence low quality but supportive; guidelines list it as an option, not first-line." },
      { use: "Texture and pores", grade: "B", note: "Consistent cosmetic-trial improvement in surface smoothness." },
      { use: "Keratosis pilaris and body roughness", grade: "C", note: "Plausible keratolytic effect; few controlled trials." },
    ],
    howToUse: "Cleanser or leave-on once daily; 2% leave-on a few times a week if using a retinoid. Do not stack with other acids while adjusting.",
    sideEffects: ["Dryness and tightness", "Stinging", "Mild peeling"],
    cautions: "Aspirin allergy is a reason to avoid it. Large-area use of high strengths, especially in children, risks salicylate absorption. Increases sun sensitivity.",
    access: "Inexpensive OTC in every price tier; concentration and pH matter more than brand.",
    regulatory: "OTC drug active for acne at 0.5–2% under FDA's monograph; also permitted as a cosmetic ingredient. FDA notes cosmetic BHA products should carry sun-protection advice.",
    trendNote: "The 'exfoliate daily' era produced a wave of over-exfoliated barriers; the trends desk covers skin cycling as the correction.",
    reviewed: REVIEWED,
    sources: [src.pmCochraneAcne, src.fdaBha, src.aadAcneGuideline, src.aadAcneWontClear],
    related: { ingredients: ["benzoyl-peroxide", "alpha-hydroxy-acids", "azelaic-acid"], trends: ["skin-cycling"] },
  },
  {
    slug: "clascoterone",
    name: "Clascoterone",
    family: "Hormonal acne actives",
    evidence: "A",
    jobs: ["Acne in adults and teens", "Hormonal-pattern acne", "Acne when oral hormonal options are unwanted"],
    watchFor: "Brand-only and expensive, with prior authorization common. Modest effect size per trial; the appeal is a new mechanism usable by anyone 12 and older.",
    summary: "The first topical androgen-receptor blocker for acne, approved in 2020. A real new option with phase 3 evidence, priced like one.",
    aliases: ["Winlevi", "clascoterone cream", "topical antiandrogen"],
    status: "Prescription (U.S.)",
    forms: ["1% cream (Rx, brand only)"],
    uses: [
      { use: "Facial acne, age 12 and older", grade: "A", note: "Two phase 3 randomized trials showed more treatment success than vehicle at 12 weeks; effect sizes were moderate." },
      { use: "Truncal acne", grade: "C", note: "Not studied in the approval trials." },
    ],
    howToUse: "Thin layer twice daily to affected areas; can be combined with a retinoid or benzoyl peroxide. Judge at 12 weeks.",
    sideEffects: ["Redness and scaling", "Itching", "Rare local HPA-axis suppression signal in labeling with large-area use"],
    cautions: "Not studied in pregnancy. Labeling notes potential adrenal suppression with extensive use; use as directed on the face.",
    access: "Brand-only with a high list price; manufacturer copay programs and insurance requirements determine real cost.",
    regulatory: "FDA-approved prescription drug (2020) for acne in patients 12 and older. Approved in some other markets; not available in many.",
    trendNote: "Marketed as 'topical spironolactone'; it is a different molecule with its own trials.",
    reviewed: REVIEWED,
    sources: [dailymed("clascoterone", "clascoterone"), src.pmClascoterone, src.aadAcneGuideline],
    related: { ingredients: ["adapalene", "benzoyl-peroxide"] },
  },
  {
    slug: "clindamycin-topical",
    name: "Topical clindamycin",
    family: "Antimicrobial acne actives",
    evidence: "A",
    jobs: ["Inflammatory acne", "Combination therapy"],
    watchFor: "Never alone. Guidelines are explicit: pair with benzoyl peroxide to prevent resistant bacteria, and stop once inflammation is controlled.",
    summary: "Effective against inflammatory acne in combination, and a resistance problem when used solo. Fixed combinations exist precisely to prevent that.",
    aliases: ["Cleocin T", "clindamycin gel", "clindamycin/benzoyl peroxide", "Onexton", "Ziana", "Cabtreo"],
    status: "Prescription (U.S.)",
    forms: ["1% gel, lotion, solution, and foam (Rx, generic)", "Fixed combinations with benzoyl peroxide, tretinoin, or both (Rx)"],
    uses: [
      { use: "Inflammatory acne with benzoyl peroxide", grade: "A", note: "Combination products have strong randomized evidence; the 2024 guideline strongly recommends against monotherapy." },
      { use: "Rosacea", grade: "C", note: "Off-label with weak evidence; metronidazole, ivermectin, and azelaic acid are preferred." },
    ],
    howToUse: "Once or twice daily on affected areas, always with benzoyl peroxide (combined product or separate application). Reassess at 12 weeks and taper off when clear.",
    sideEffects: ["Dryness and peeling", "Stinging", "Rare diarrhea or colitis reported with topical use"],
    cautions: "History of antibiotic-associated colitis is a reason to avoid. Long-term solo use breeds resistance that affects future treatment.",
    access: "Generic gels and solutions are inexpensive; combination products vary widely and some are brand-only.",
    regulatory: "FDA-approved prescription drug for acne; prescription-only in most jurisdictions.",
    reviewed: REVIEWED,
    sources: [dailymed("clindamycin phosphate topical", "topical clindamycin"), src.aadAcneGuideline, src.aadAcneGuidelinePm],
    related: { ingredients: ["benzoyl-peroxide", "adapalene"] },
  },
  {
    slug: "dapsone-gel",
    name: "Dapsone gel",
    family: "Anti-inflammatory acne actives",
    evidence: "B",
    jobs: ["Inflammatory acne", "Adult female acne", "Sensitive skin that cannot tolerate retinoids"],
    watchFor: "Turns orange-brown temporarily when layered with benzoyl peroxide. Slower and milder than retinoids; a good option when tolerability is the problem.",
    summary: "A gentle anti-inflammatory gel with randomized evidence for inflammatory acne, most useful for people who cannot tolerate stronger actives.",
    aliases: ["Aczone", "dapsone 5%", "dapsone 7.5%"],
    status: "Prescription (U.S.)",
    forms: ["5% gel twice daily (Rx, generic)", "7.5% gel once daily (Rx)"],
    uses: [
      { use: "Inflammatory acne", grade: "B", note: "Vehicle-controlled trials show modest lesion reduction, with some analyses suggesting more benefit in adult women." },
      { use: "Comedonal acne", grade: "C", note: "Weaker effect on non-inflamed lesions." },
    ],
    howToUse: "Pea-sized amount to affected areas once or twice daily depending on strength. Apply benzoyl peroxide at a different time to avoid discoloration.",
    sideEffects: ["Dryness and redness", "Oiliness or peeling", "Temporary orange staining with benzoyl peroxide"],
    cautions: "Labeling notes hemolysis risk in G6PD deficiency is low with topical use but present; tell the prescriber about G6PD deficiency or methemoglobinemia history.",
    access: "Generic 5% gel is reasonably priced; 7.5% is often brand-only with prior authorization.",
    regulatory: "FDA-approved prescription drug for acne in patients 9 (7.5%) or 12 (5%) and older.",
    reviewed: REVIEWED,
    sources: [dailymed("dapsone gel", "dapsone gel"), src.aadAcneGuideline, src.aadAdultAcne],
    related: { ingredients: ["azelaic-acid", "clascoterone"] },
  },

  // ------------------------------------------------------------------
  // Pigment and redness
  // ------------------------------------------------------------------
  {
    slug: "azelaic-acid",
    name: "Azelaic acid",
    family: "Dicarboxylic acid",
    evidence: "A",
    jobs: ["Rosacea bumps and redness", "Acne", "Melasma and post-inflammatory marks", "Pregnancy-compatible option"],
    watchFor: "Tingling and itch for the first weeks are normal. Prescription 15–20% is a drug; 10% cosmetics are a different, weaker product with the same name.",
    summary: "The quiet multitasker: FDA-approved for rosacea and acne, useful for pigment, and one of the few actives dermatologists are comfortable recommending in pregnancy.",
    aliases: ["Finacea", "Azelex", "azelaic acid gel", "azelaic acid foam", "azelaic acid cream", "10% azelaic acid"],
    status: "Prescription or cosmetic (U.S.)",
    forms: ["15% gel and foam (Rx, generic gel; approved for rosacea)", "20% cream (Rx, generic; approved for acne)", "10% and lower in cosmetics"],
    uses: [
      { use: "Papulopustular rosacea", grade: "A", note: "FDA-approved; network meta-analyses rank it with metronidazole and ivermectin for inflammatory lesions." },
      { use: "Acne", grade: "A", note: "FDA-approved 20% cream; Cochrane 2020 found moderate-quality evidence it works, somewhat less than benzoyl peroxide or retinoids." },
      { use: "Melasma and post-inflammatory hyperpigmentation", grade: "B", note: "Randomized comparisons show benefit similar to hydroquinone 4% in some trials, with slower onset." },
      { use: "Cosmetic 10% products", grade: "C", note: "Lower strength and different vehicles; evidence is inferred from prescription data." },
    ],
    howToUse: "Thin layer twice daily (rosacea and acne) or nightly alongside sunscreen for pigment. Expect 8–12 weeks. Can be layered with retinoids once tolerated.",
    sideEffects: ["Tingling, burning, or itch early on", "Dryness", "Rare lightening of surrounding skin in darker tones"],
    cautions: "Generally considered compatible with pregnancy and breastfeeding, which is why it anchors many pregnancy routines; confirm with your clinician. Mild hypopigmentation can occur around treated spots.",
    access: "Generic 15% gel and 20% cream are inexpensive with a prescription; the foam is brand-only. Cosmetic 10% products are OTC at a wide range of prices.",
    regulatory: "FDA-approved prescription drug (15% for rosacea, 20% for acne). Cosmetic azelaic acid at 10% or less is sold without review. Some countries sell 15–20% OTC.",
    trendNote: "'Azelaic acid for everything' is a fair trend as trends go; the prescription strength is what the evidence describes.",
    reviewed: REVIEWED,
    sources: [dailymed("azelaic acid", "azelaic acid"), src.pmAzelaicSr, src.pmCochraneAcne, src.pmRosaceaNma, src.aadMelasma, src.aadRosacea],
    related: { dispatches: ["basic-skincare-vehicle-arms-review"], ingredients: ["metronidazole", "ivermectin-cream", "niacinamide", "tranexamic-acid"] },
  },
  {
    slug: "hydroquinone",
    name: "Hydroquinone",
    family: "Tyrosinase inhibitors",
    evidence: "A",
    jobs: ["Melasma", "Post-inflammatory hyperpigmentation", "Dark spots"],
    watchFor: "Prescription-only in the U.S. since 2020; any OTC or imported 'whitening' cream containing it is unapproved. Use in cycles of a few months, never continuously.",
    summary: "The most effective single lightening agent and the most regulated. Works in supervised cycles; misused, it causes the very discoloration people are trying to fix.",
    aliases: ["Tri-Luma", "HQ 4%", "skin bleaching cream", "hydroquinone cream", "Kligman formula"],
    status: "Prescription (U.S.)",
    forms: ["4% cream (Rx; most products are marketed without FDA approval)", "Triple combination 4% hydroquinone / 0.05% tretinoin / 0.01% fluocinolone (Rx, the only FDA-approved product)", "Compounded higher strengths (Rx)"],
    uses: [
      { use: "Melasma", grade: "A", note: "Triple-combination cream is FDA-approved for moderate to severe melasma; network meta-analyses rank hydroquinone-based regimens among the most effective." },
      { use: "Post-inflammatory hyperpigmentation", grade: "B", note: "Widely used with supportive trials; tretinoin and azelaic acid are alternatives." },
    ],
    howToUse: "Thin layer to the spots nightly for 8–12 weeks, then a break; daily broad-spectrum sunscreen is mandatory or the pigment returns. Many clinicians alternate with azelaic acid or tranexamic acid during breaks.",
    sideEffects: ["Irritation and redness", "Halo lightening around spots", "Exogenous ochronosis (blue-black discoloration) with prolonged or high-strength use"],
    cautions: "Not recommended in pregnancy. Stop and seek care if darkening or blue-black patches appear. Imported skin-lightening products have been found to contain mercury and undisclosed hydroquinone.",
    access: "Prescription 4% cream is inexpensive; the approved triple-combination cream is costly and often not covered. Telehealth compounding is common; check the pharmacy.",
    regulatory: "Under the 2020 CARES Act, OTC hydroquinone is no longer legally marketed in the U.S.; FDA issued warning letters in 2022 and says the triple-combination cream is the only approved hydroquinone product. Banned in E.U. cosmetics; prescription elsewhere.",
    trendNote: "Trending in the wrong direction: 'glow' creams from overseas marketplaces are where FDA keeps finding mercury and hydroquinone.",
    reviewed: REVIEWED,
    sources: [src.fdaSkinLightening, src.fdaSkinFacts, dailymed("hydroquinone", "hydroquinone"), src.pmOchronosis, src.pmMelasmaNma, src.aadMelasma],
    related: { dispatches: ["us-skin-lightening-mercury-warning-2026"], ingredients: ["azelaic-acid", "tranexamic-acid", "tretinoin"] },
  },
  {
    slug: "tranexamic-acid",
    name: "Tranexamic acid (topical)",
    family: "Pigment modulators",
    evidence: "B",
    jobs: ["Melasma", "Post-inflammatory marks", "Hydroquinone-free maintenance"],
    watchFor: "The oral form is the one with the strongest evidence and real clotting cautions; topical 2–5% is gentler and weaker. Don't confuse the two when reading trial headlines.",
    summary: "A clot-stabilizing drug repurposed for pigment. Topically it is a reasonable, gentle melasma option; orally it is a prescription with vascular-risk screening.",
    aliases: ["TXA", "tranexamic acid serum", "tranexamic acid cream", "oral tranexamic acid"],
    status: "Cosmetic ingredient",
    forms: ["2–5% serums and creams (cosmetic)", "Compounded topical (Rx)", "Oral tablets for melasma (Rx, off-label)"],
    uses: [
      { use: "Melasma (topical)", grade: "B", note: "Randomized trials and a 2024 meta-analysis show benefit, generally less than oral tranexamic acid or hydroquinone, with fewer side effects." },
      { use: "Melasma (oral, off-label)", grade: "B", note: "Meta-analyses show meaningful improvement; requires screening for clotting risk and prescriber follow-up." },
      { use: "Post-inflammatory hyperpigmentation", grade: "C", note: "Extrapolated from melasma data." },
    ],
    howToUse: "Topical: once or twice daily under sunscreen for at least 12 weeks; combine with retinoids, azelaic acid, or vitamin C. Oral use is a prescriber decision.",
    sideEffects: ["Mild irritation (topical)", "Dryness", "Oral: headache, GI upset, and rare clotting events"],
    cautions: "Oral tranexamic acid is avoided with a history of clots, hormonal contraception in some cases, or clotting disorders. Topical use has no such signal but lacks pregnancy data.",
    access: "Topical products span drugstore to prestige pricing; the molecule is inexpensive. Oral tablets are generic and cheap with a prescription.",
    regulatory: "Topical tranexamic acid is a cosmetic ingredient in the U.S. with no approved skin indication; oral tablets are FDA-approved for heavy menstrual bleeding and used off-label for melasma.",
    trendNote: "The pigment ingredient of the moment, often stacked with everything else; layering more brighteners does not multiply results.",
    reviewed: REVIEWED,
    sources: [src.pmTxaMa, src.pmMelasmaNma, src.aadMelasma],
    related: { ingredients: ["hydroquinone", "azelaic-acid", "vitamin-c", "niacinamide"] },
  },
  {
    slug: "vitamin-c",
    name: "Vitamin C (L-ascorbic acid and derivatives)",
    family: "Antioxidants",
    evidence: "B",
    jobs: ["Photoprotection alongside sunscreen", "Brightening", "Fine lines", "Post-inflammatory marks"],
    watchFor: "L-ascorbic acid oxidizes: if the serum has turned orange-brown, it is spent. Derivatives are stabler but less proven. Stinging at low pH is common.",
    summary: "The best-studied cosmetic antioxidant, with modest, real effects on pigment and photoaging when the formula is stable and the concentration meaningful.",
    aliases: ["ascorbic acid", "L-ascorbic acid", "vitamin C serum", "ascorbyl glucoside", "THD ascorbate", "sodium ascorbyl phosphate", "magnesium ascorbyl phosphate"],
    status: "Cosmetic ingredient",
    forms: ["L-ascorbic acid 10–20% serums at low pH", "Derivatives (ascorbyl glucoside, THD ascorbate, ascorbyl phosphates) at various strengths", "Combinations with vitamin E and ferulic acid"],
    uses: [
      { use: "Photoaging and fine lines", grade: "B", note: "A 2023 systematic review found improvement in small vehicle-controlled trials, mostly with 10–20% L-ascorbic acid over 12 weeks or more." },
      { use: "Melasma and dark spots", grade: "B", note: "Modest benefit alone; useful alongside stronger agents." },
      { use: "Antioxidant protection under sunscreen", grade: "B", note: "Reduces UV-induced redness and damage markers in controlled studies; not a substitute for sunscreen." },
    ],
    howToUse: "A few drops in the morning on clean skin, then moisturizer and sunscreen. Store away from light and heat; buy small bottles.",
    sideEffects: ["Stinging and redness at low pH", "Yellow staining of skin or fabric from oxidized product", "Breakouts with some oily vehicles"],
    cautions: "Sensitive or rosacea-prone skin often tolerates derivatives better than L-ascorbic acid. Compatible with pregnancy.",
    access: "Price bears no relationship to concentration or stability; look for concentration, pH, and opaque airless packaging.",
    regulatory: "Cosmetic ingredient in all major markets; no premarket review of claims.",
    trendNote: "'Vitamin C at 30%' and DIY powders are the trend edge; higher concentration adds irritation, not effect.",
    reviewed: REVIEWED,
    sources: [src.pmVitC, src.pmDelphi, src.pmCosmeceuticals, src.fdaWrinkle],
    related: { ingredients: ["sunscreen", "niacinamide", "tranexamic-acid"] },
  },
  {
    slug: "niacinamide",
    name: "Niacinamide",
    family: "Vitamin B3",
    evidence: "B",
    jobs: ["Barrier support", "Redness", "Oil and pore appearance", "Uneven tone"],
    watchFor: "2–5% is where the evidence lives; 10–20% adds flushing and stinging for many people without added benefit. It is not the same as niacin.",
    summary: "A well-tolerated, well-supported supporting ingredient: modest improvements in barrier, redness, oil, and pigment, with few downsides at sensible strength.",
    aliases: ["nicotinamide", "vitamin B3", "niacinamide serum", "10% niacinamide"],
    status: "Cosmetic ingredient",
    forms: ["2–5% in moisturizers and serums (most evidence)", "10% serums (popular; less studied)", "Oral nicotinamide for skin cancer prevention (supplement, medical advice needed)"],
    uses: [
      { use: "Barrier function and redness", grade: "B", note: "Controlled studies show reduced water loss and improved barrier markers at 2–5%." },
      { use: "Hyperpigmentation", grade: "B", note: "Reduces melanosome transfer; trials show modest lightening over 8–12 weeks." },
      { use: "Acne", grade: "B", note: "Cochrane 2020 found low-quality evidence for topical nicotinamide comparable to clindamycin in small trials." },
      { use: "Pore size and oil", grade: "C", note: "Small studies report reduced sebum and pore appearance." },
    ],
    howToUse: "Once or twice daily in a moisturizer or serum; layers with almost everything. Starting with a low-concentration moisturizer avoids flushing.",
    sideEffects: ["Flushing or warmth at high concentrations", "Stinging", "Rare irritant dermatitis"],
    cautions: "Compatible with pregnancy. Oral nicotinamide has its own evidence for reducing non-melanoma skin cancer in high-risk people and should be discussed with a clinician, not started from a skincare video.",
    access: "Inexpensive and in most drugstore moisturizers; paying more for a higher percentage rarely pays off.",
    regulatory: "Cosmetic ingredient with no premarket review.",
    trendNote: "A fixture of 'skinimalism' routines and a frequent victim of the 'more percent is better' fallacy.",
    reviewed: REVIEWED,
    sources: [src.pmNiacinamide, src.pmNiacinamide2, src.pmCochraneAcne, src.pmDelphi],
    related: { guides: ["skin-barrier-explained"], ingredients: ["ceramides", "azelaic-acid", "vitamin-c"] },
  },
  {
    slug: "metronidazole",
    name: "Metronidazole (topical)",
    family: "Rosacea prescriptions",
    evidence: "A",
    jobs: ["Rosacea bumps and pustules", "Maintenance after oral therapy"],
    watchFor: "Treats the bumps, not the background redness or visible vessels; those need vascular lasers or brimonidine-type drugs. Expect 6–8 weeks.",
    summary: "The long-standing first-line prescription for papulopustular rosacea, cheap and well tolerated, now joined and in some analyses outperformed by ivermectin.",
    aliases: ["MetroGel", "MetroCream", "Noritate", "metronidazole gel", "metronidazole cream"],
    status: "Prescription (U.S.)",
    forms: ["0.75% gel, cream, and lotion (Rx, generic)", "1% gel and cream (Rx)"],
    uses: [
      { use: "Papulopustular rosacea", grade: "A", note: "FDA-approved with decades of trial data; network meta-analyses place it slightly behind ivermectin for lesion clearance." },
      { use: "Persistent facial redness", grade: "C", note: "Little effect on background erythema or telangiectasia." },
    ],
    howToUse: "Thin layer once or twice daily to affected areas; continue for maintenance once clear. Pair with gentle cleansing, sunscreen, and trigger management.",
    sideEffects: ["Dryness", "Stinging or burning", "Watery eyes if applied near the eyes"],
    cautions: "Generally considered acceptable in pregnancy for topical use; confirm with your clinician. Avoid contact with eyes.",
    access: "Generic 0.75% is inexpensive and widely covered.",
    regulatory: "FDA-approved prescription drug for inflammatory rosacea lesions; prescription-only in most jurisdictions.",
    reviewed: REVIEWED,
    sources: [dailymed("metronidazole topical", "topical metronidazole"), src.pmRosaceaNma, src.pmRosaceaTopicalNma, src.aadRosacea],
    related: { ingredients: ["ivermectin-cream", "azelaic-acid"], procedures: ["vascular-pigment-lasers", "ipl-photofacial"] },
  },
  {
    slug: "ivermectin-cream",
    name: "Ivermectin 1% cream",
    family: "Rosacea prescriptions",
    evidence: "A",
    jobs: ["Rosacea bumps and pustules", "Demodex-associated rosacea"],
    watchFor: "Now generic, which removed the main reason to start with metronidazole. Works on inflammation and mites, not on flushing or vessels.",
    summary: "A once-daily rosacea cream that ranks at or near the top of network meta-analyses for inflammatory lesions, with a good tolerability profile.",
    aliases: ["Soolantra", "ivermectin cream", "topical ivermectin"],
    status: "Prescription (U.S.)",
    forms: ["1% cream once daily (Rx, generic)"],
    uses: [
      { use: "Papulopustular rosacea", grade: "A", note: "Phase 3 trials versus vehicle and versus metronidazole, plus 2025–2026 network meta-analyses, support it as a top topical option." },
      { use: "Redness and flushing", grade: "C", note: "Not a treatment for vascular symptoms." },
    ],
    howToUse: "Pea-sized amount to the face once daily for at least 12 weeks; many people continue as maintenance.",
    sideEffects: ["Burning or stinging", "Dryness", "Itch"],
    cautions: "Limited pregnancy data; discuss with your clinician. Not the oral drug and not for parasitic infections.",
    access: "Generic cream has made it affordable; brand pricing remains high without coverage.",
    regulatory: "FDA-approved prescription drug for inflammatory rosacea lesions; prescription-only elsewhere.",
    reviewed: REVIEWED,
    sources: [dailymed("ivermectin cream", "ivermectin cream"), src.pmRosaceaNma, src.pmRosaceaTopicalNma, src.aadRosacea],
    related: { ingredients: ["metronidazole", "azelaic-acid"], procedures: ["vascular-pigment-lasers"] },
  },

  // ------------------------------------------------------------------
  // Barrier and hydration
  // ------------------------------------------------------------------
  {
    slug: "ceramides",
    name: "Ceramides",
    family: "Barrier lipids",
    evidence: "B",
    jobs: ["Dry and eczema-prone skin", "Barrier repair after actives", "Sensitive skin maintenance"],
    watchFor: "A moisturizer's overall formula matters more than the word 'ceramide' on the front. Ratio-balanced lipid blends are the ones with trial data.",
    summary: "Structural skin lipids that good moisturizers replace. Solid evidence for barrier support in dry and eczema-prone skin; marketing has outrun the difference between formulas.",
    aliases: ["ceramide NP", "ceramide AP", "ceramide EOP", "phytosphingosine", "barrier cream"],
    status: "Cosmetic ingredient",
    forms: ["Moisturizers with ceramides plus cholesterol and fatty acids", "Ceramide-dominant prescription barrier creams (Rx, device-classified)"],
    uses: [
      { use: "Dry skin and barrier repair", grade: "B", note: "Controlled studies, including a 2025 trial, show restored ceramide profiles and reduced water loss with physiological lipid blends." },
      { use: "Atopic dermatitis maintenance", grade: "B", note: "Guidelines recommend regular moisturizing; ceramide-containing products perform well, without clear superiority over other good emollients." },
      { use: "Anti-aging claims", grade: "C", note: "Hydration improves appearance; no evidence of structural change." },
    ],
    howToUse: "Apply to damp skin after cleansing and after actives; more often in winter and during retinoid adjustment.",
    sideEffects: ["Rare irritation from other formula ingredients", "Occlusive feel in oily skin"],
    cautions: "None specific; check for fragrance and essential oils if reactive.",
    access: "Effective ceramide moisturizers exist at every price; drugstore brands have trial data.",
    regulatory: "Cosmetic ingredients; a few prescription barrier creams are regulated as devices.",
    trendNote: "The 'barrier repair' era made ceramides a buzzword; the boring advice (moisturize, stop over-exfoliating) is the evidence-based part.",
    reviewed: REVIEWED,
    sources: [src.pmCeramideBjd, src.aadAdGuideline, src.aadDrySkin],
    related: { guides: ["skin-barrier-explained"], dispatches: ["ceramide-np-c15-sensitive-skin-trial"], ingredients: ["niacinamide", "petrolatum", "hyaluronic-acid"] },
  },
  {
    slug: "hyaluronic-acid",
    name: "Hyaluronic acid (topical)",
    family: "Humectants",
    evidence: "B",
    jobs: ["Surface hydration", "Plumper look of fine lines", "Layering under moisturizer"],
    watchFor: "It holds water where it sits; in dry air without a moisturizer on top it can leave skin feeling tighter. Injectable hyaluronic acid is a different product entirely.",
    summary: "A reliable surface humectant with short-lived plumping. Real, modest, and not the same thing as the filler that shares its name.",
    aliases: ["sodium hyaluronate", "HA serum", "hyaluronic acid serum", "multi-weight hyaluronic acid"],
    status: "Cosmetic ingredient",
    forms: ["Serums and moisturizers with sodium hyaluronate at various molecular weights"],
    uses: [
      { use: "Skin hydration and smoothness", grade: "B", note: "Randomized trials, including a 2024 double-blind study in dry skin, show improved hydration and roughness over weeks." },
      { use: "Fine lines", grade: "C", note: "Temporary plumping from water; no structural remodeling." },
    ],
    howToUse: "On damp skin, then seal with a moisturizer. Works best under an occlusive in dry climates.",
    sideEffects: ["Rare irritation from preservatives or fragrance", "Tightness if used alone in dry air"],
    cautions: "Compatible with pregnancy and all actives.",
    access: "Inexpensive in most moisturizers; premium 'multi-weight' claims lack comparative evidence.",
    regulatory: "Cosmetic ingredient; the injectable fillers are FDA-regulated medical devices.",
    trendNote: "Skin flooding and 'seven-skin' layering routines are largely about this molecule.",
    reviewed: REVIEWED,
    sources: [src.pmHaReview, src.pmHaXerosis, src.aadDrySkin],
    related: { ingredients: ["ceramides", "petrolatum"], procedures: ["hyaluronic-acid-fillers", "skin-boosters"], trends: ["skin-flooding"] },
  },
  {
    slug: "petrolatum",
    name: "Petrolatum (petroleum jelly)",
    family: "Occlusives",
    evidence: "A",
    jobs: ["Sealing in moisture", "Wound and post-procedure care", "Slugging", "Lips, hands, and heels"],
    watchFor: "It does not moisturize on its own; it stops water leaving. On acne-prone skin, an all-over layer can trap oil and products underneath.",
    summary: "The most effective occlusive in dermatology, backed by wound-care trials and cheap enough to be boring. The trend called slugging is this ingredient used as directed.",
    aliases: ["Vaseline", "Aquaphor", "petroleum jelly", "white petrolatum", "occlusive", "slugging"],
    status: "OTC drug (U.S.)",
    forms: ["100% white petrolatum", "Petrolatum-based ointments with lanolin, glycerin, or panthenol"],
    uses: [
      { use: "Dry skin and barrier repair", grade: "A", note: "Reduces water loss more than any other common ingredient; studies show it also induces barrier-repair gene expression." },
      { use: "Wound and post-procedure care", grade: "A", note: "Standard of care after procedures and for minor wounds; performs as well as antibiotic ointment with fewer allergies." },
      { use: "Slugging over a routine", grade: "B", note: "Sensible for dry or irritated skin; dermatologists recommend it, with cautions for acne-prone skin." },
    ],
    howToUse: "Thin layer as the last step over a moisturizer, or on lips, hands, and heels. Skip on active acne areas. Do not layer over strong actives you have not tolerated.",
    sideEffects: ["Trapped heat or sweat", "Breakouts in acne-prone areas", "Rare folliculitis under thick layers"],
    cautions: "Avoid inside the nose long term and over infected skin. Cosmetic-grade petrolatum is highly refined; the contamination concerns that apply to industrial grades do not apply to it.",
    access: "Among the cheapest skincare products that exist.",
    regulatory: "OTC skin protectant under FDA's monograph; cosmetic-grade petrolatum in the E.U. must meet purity requirements.",
    trendNote: "Slugging brought it back; the trends desk covers who it suits.",
    reviewed: REVIEWED,
    sources: [src.aadPetroleum, src.pmPetrolatum, src.aadDrySkin],
    related: { guides: ["skin-barrier-explained"], ingredients: ["ceramides", "hyaluronic-acid", "urea"], trends: ["slugging", "beef-tallow"] },
  },
  {
    slug: "urea",
    name: "Urea",
    family: "Humectants and keratolytics",
    evidence: "A",
    jobs: ["Very dry, rough skin", "Cracked heels and feet", "Keratosis pilaris", "Thick scaly patches"],
    watchFor: "Concentration sets the job: 5–10% hydrates, 20–40% dissolves thick skin and can sting on cracks. Not for broken or inflamed facial skin at high strengths.",
    summary: "An unglamorous humectant that outperforms most moisturizers on severely dry skin, with randomized trials on diabetic feet and xerosis.",
    aliases: ["urea cream", "carbamide", "10% urea", "40% urea", "Eucerin urea", "keratolytic"],
    status: "OTC drug or prescription (U.S.)",
    forms: ["5–10% creams and lotions (cosmetic/OTC)", "20–40% creams and gels (OTC or Rx keratolytic)"],
    uses: [
      { use: "Severe dry skin and cracked feet", grade: "A", note: "Randomized placebo-controlled trials, including in diabetes, show meaningful improvement in xerosis and fissures." },
      { use: "Keratosis pilaris and rough patches", grade: "B", note: "Widely used with supportive but smaller evidence." },
      { use: "Thick nails and calluses (40%)", grade: "B", note: "Established keratolytic use." },
    ],
    howToUse: "Low strengths once or twice daily on the body; high strengths only on thick skin, avoiding cracks and folds. Face use at 5% or less.",
    sideEffects: ["Stinging on broken skin", "Redness", "Excess softening if over-applied"],
    cautions: "Avoid high strengths on the face or genitals. Compatible with pregnancy.",
    access: "Inexpensive; European brands with high urea content are widely imported.",
    regulatory: "Cosmetic at low strengths; higher-strength keratolytics are OTC or prescription drugs depending on labeling.",
    reviewed: REVIEWED,
    sources: [src.pmUrea, src.aadDrySkin],
    related: { ingredients: ["petrolatum", "ceramides", "salicylic-acid"] },
  },
  {
    slug: "ectoin",
    name: "Ectoin",
    family: "Osmolytes",
    evidence: "C",
    jobs: ["Soothing", "Hydration", "Reactive skin"],
    watchFor: "Most human trials are small and manufacturer-supported. A comfortable ingredient with a promise that outruns its evidence.",
    summary: "A bacterial osmolyte marketed as a barrier-strengthening, anti-pollution active. Pleasant and well tolerated; the controlled evidence is early.",
    aliases: ["ectoine", "ectoin serum"],
    status: "Cosmetic ingredient",
    forms: ["0.5–2% serums and creams", "Eye drops and nasal sprays as medical devices in some countries"],
    uses: [
      { use: "Soothing irritated skin", grade: "C", note: "Small studies and in vitro work; few independent randomized trials." },
      { use: "Barrier support", grade: "C", note: "Plausible osmoprotective mechanism; limited comparative data." },
    ],
    howToUse: "Once or twice daily; layers with anything.",
    sideEffects: ["Rare irritation from the vehicle"],
    cautions: "None known.",
    access: "Mid to premium pricing with no evidence-based reason for the premium.",
    regulatory: "Cosmetic ingredient; some ectoin products are classed as medical devices in the E.U. for eyes and nose.",
    reviewed: REVIEWED,
    sources: [src.pmCosmeceuticals, src.fdaWrinkle],
    related: { ingredients: ["niacinamide", "ceramides"] },
  },

  // ------------------------------------------------------------------
  // Sun protection
  // ------------------------------------------------------------------
  {
    slug: "sunscreen",
    name: "Sunscreen (mineral and chemical filters)",
    family: "UV filters",
    evidence: "A",
    jobs: ["Skin cancer prevention", "Preventing photoaging and pigment", "Protecting treated skin"],
    watchFor: "Application amount is where most protection is lost; most people apply a quarter to half of the tested dose. 'Mineral' and 'chemical' describe mechanism, not safety rank.",
    summary: "The one daily product with randomized evidence for preventing skin cancer and visible aging. In the U.S. it is an OTC drug, which is why new filters arrive slowly.",
    aliases: ["SPF", "zinc oxide", "titanium dioxide", "avobenzone", "octocrylene", "mineral sunscreen", "chemical sunscreen", "Korean sunscreen", "tinted sunscreen"],
    status: "OTC drug (U.S.)",
    forms: ["Mineral (zinc oxide, titanium dioxide)", "Organic filters (avobenzone, octocrylene, homosalate, octisalate, and now bemotrizinol)", "Tinted formulas with iron oxides for visible-light protection"],
    uses: [
      { use: "Melanoma and skin cancer prevention", grade: "A", note: "The Nambour randomized trial found reduced melanoma with regular daily use over long follow-up." },
      { use: "Preventing photoaging", grade: "A", note: "A randomized trial found daily sunscreen users showed no detectable increase in skin aging over 4.5 years versus discretionary use." },
      { use: "Melasma and pigment control", grade: "B", note: "Tinted, iron-oxide sunscreens add visible-light protection that matters for melasma." },
    ],
    howToUse: "Broad-spectrum SPF 30 or higher, about a quarter teaspoon for the face, every morning, reapplied every two hours outdoors. Under makeup, a tinted mineral formula doubles as base.",
    sideEffects: ["Stinging near the eyes with some organic filters", "White cast from mineral filters on deeper skin tones", "Rare allergic contact dermatitis"],
    cautions: "Mineral filters are the default for infants over 6 months and reactive skin. Some organic filters are absorbed systemically; FDA has asked for more data, not ordered them off the market.",
    access: "Effective sunscreens exist at drugstore prices; texture, tint, and finish are worth paying for because they drive daily use. Imported Asian sunscreens use filters not yet approved in the U.S.",
    regulatory: "OTC drugs regulated under FDA's sunscreen monograph; zinc oxide and titanium dioxide are recognized as safe and effective, and bemotrizinol became the first new U.S. filter in decades in 2026. The E.U., Australia, Japan, and Korea approve more filters, which is why imported sunscreens differ.",
    trendNote: "Sunscreen contouring, 'chemical filters are toxic' posts, and Korean sunscreen imports are all in the trends desk.",
    reviewed: REVIEWED,
    sources: [src.fdaSunscreen, src.fdaSunscreenRulemaking, src.aadSunscreenFaq, src.aadSunscreenSelect, src.pmSunscreenMelanoma, src.pmSunscreenAging],
    related: { dispatches: ["bemotrizinol-us-sunscreen-filter", "australia-sunscreen-testing-consultation"], ingredients: ["bemotrizinol", "vitamin-c"], trends: ["sunscreen-contouring", "korean-sunscreen-imports"] },
  },
  {
    slug: "bemotrizinol",
    name: "Bemotrizinol",
    family: "UV filters",
    evidence: "A",
    jobs: ["Broad-spectrum UVA and UVB protection", "Photostable sunscreen formulas"],
    watchFor: "The regulatory change applies to the filter's permission in the U.S.; products still need to be formulated, tested, labeled, and sold before it changes what you can buy.",
    summary: "A photostable broad-spectrum filter used for years abroad and now permitted in U.S. over-the-counter sunscreens. Permission is not the same as shelf availability.",
    aliases: ["Tinosorb S", "bis-ethylhexyloxyphenol methoxyphenyl triazine", "BEMT"],
    status: "OTC drug (U.S.)",
    forms: ["Sunscreen filter up to the concentration set in the FDA order", "Long used at up to 10% in E.U., Australian, and Asian sunscreens"],
    uses: [
      { use: "Broad-spectrum UV filtering", grade: "A", note: "Extensive international use and regulatory review; FDA's 2026 final order established it as generally recognized as safe and effective." },
    ],
    howToUse: "As part of a finished sunscreen applied like any other; the filter itself is not sold to consumers.",
    sideEffects: ["Low irritation and sensitization rates reported internationally"],
    cautions: "None specific beyond usual sunscreen guidance.",
    access: "U.S. products containing it will follow the order on manufacturers' timelines; imported sunscreens have contained it for years.",
    regulatory: "Permitted in U.S. OTC sunscreens by FDA final order in 2026; approved in the E.U., Australia, Japan, Korea, and elsewhere since the early 2000s.",
    reviewed: REVIEWED,
    sources: [src.fdaSunscreenRulemaking, src.fdaSunscreen, src.aadSunscreenSelect],
    related: { dispatches: ["bemotrizinol-us-sunscreen-filter"], ingredients: ["sunscreen"], trends: ["korean-sunscreen-imports"] },
  },

  // ------------------------------------------------------------------
  // Exfoliants and cosmeceuticals
  // ------------------------------------------------------------------
  {
    slug: "alpha-hydroxy-acids",
    name: "Alpha hydroxy acids (glycolic, lactic, mandelic)",
    family: "Hydroxy acids",
    evidence: "B",
    jobs: ["Surface texture", "Dullness", "Mild pigment", "Keratosis pilaris and body roughness"],
    watchFor: "Effect and irritation track concentration and pH together. FDA's guidance for cosmetics is 10% or less at pH 3.5 or higher; peels are a different category with their own file.",
    summary: "Water-soluble exfoliants with decent evidence for texture and tone at cosmetic strengths, and a well-documented capacity for over-use.",
    aliases: ["AHA", "glycolic acid", "lactic acid", "mandelic acid", "exfoliating toner", "acid toner"],
    status: "Cosmetic ingredient",
    forms: ["5–10% leave-on serums and toners (cosmetic)", "Lower strengths in cleansers and body lotions", "20–70% professional peels"],
    uses: [
      { use: "Texture, dullness, and mild photodamage", grade: "B", note: "Controlled cosmetic trials show smoother texture and mild pigment improvement over 8–12 weeks." },
      { use: "Acne", grade: "C", note: "Cochrane 2020 found the evidence for fruit acids in acne weak and uncertain." },
      { use: "Body roughness and keratosis pilaris", grade: "B", note: "Lactic acid lotions have supportive data for rough, dry body skin." },
    ],
    howToUse: "Two or three nights a week at 5–10%, not on retinoid nights until tolerated; daily sunscreen is essential. Mandelic acid is gentler for darker or sensitive skin.",
    sideEffects: ["Stinging and redness", "Increased sun sensitivity", "Barrier damage with daily stacking"],
    cautions: "FDA advises sun protection with AHA use; avoid on active eczema or rosacea. Compatible with pregnancy at cosmetic strengths.",
    access: "Inexpensive; concentration and pH labeling matter more than brand.",
    regulatory: "Cosmetic ingredients in the U.S.; FDA guidance recommends 10% or less at pH 3.5 or above for consumer products and sun-protection labeling. Some jurisdictions cap concentrations.",
    trendNote: "The over-exfoliation wave and the skin-cycling correction both start here.",
    reviewed: REVIEWED,
    sources: [src.fdaAha, src.pmCochraneAcne, src.pmCosmeceuticals],
    related: { ingredients: ["salicylic-acid", "retinol-retinal"], procedures: ["superficial-chemical-peel"], trends: ["skin-cycling"] },
  },
  {
    slug: "peptides",
    name: "Peptides (signal, carrier, and copper peptides)",
    family: "Cosmeceutical actives",
    evidence: "C",
    jobs: ["Fine lines", "Firmness claims", "Post-procedure support"],
    watchFor: "'Peptide' covers hundreds of molecules with different sizes and claims; most have never been tested in independent trials, and large peptides do not penetrate intact skin well.",
    summary: "Plausible signaling molecules with small, mostly industry-run studies. Not harmful, occasionally helpful, and priced as if the evidence were stronger.",
    aliases: ["Matrixyl", "palmitoyl pentapeptide", "copper peptides", "GHK-Cu", "argireline", "acetyl hexapeptide", "peptide serum"],
    status: "Cosmetic ingredient",
    forms: ["Serums and creams with signal peptides (palmitoyl pentapeptide and others)", "Copper tripeptide (GHK-Cu) products", "Neurotransmitter-inhibiting peptides marketed as 'topical Botox'"],
    uses: [
      { use: "Fine lines and photoaging", grade: "C", note: "A 2024 systematic review of cosmeceuticals found small, short, mostly vehicle-controlled studies with modest effects for some peptides." },
      { use: "Wound and post-laser healing (copper peptides)", grade: "C", note: "One small 2006 study after laser resurfacing; little since." },
      { use: "'Topical Botox' claims", grade: "Context", note: "No peptide replicates neuromodulator injections; surface effects are cosmetic and temporary." },
    ],
    howToUse: "Once or twice daily; avoid combining copper peptides with strong acids or vitamin C in the same layer, which can destabilize them.",
    sideEffects: ["Rare irritation or allergy", "Discoloration of some copper products when oxidized"],
    cautions: "Compatible with pregnancy. Skepticism is the main caution.",
    access: "Frequently premium-priced; the molecule cost is low.",
    regulatory: "Cosmetic ingredients; FDA notes that products claiming to alter skin structure or function are making drug claims.",
    trendNote: "Copper peptides and 'peptide layering' are in heavy rotation; the evidence has not moved with the popularity.",
    reviewed: REVIEWED,
    sources: [src.pmCosmeceuticals, src.pmCopper, src.pmDelphi, src.fdaWrinkle],
    related: { ingredients: ["retinol-retinal", "growth-factors"], procedures: ["neuromodulators"] },
  },
  {
    slug: "growth-factors",
    name: "Growth factors, PDRN, and 'regenerative' topicals",
    family: "Cosmeceutical actives",
    evidence: "C",
    jobs: ["Photoaging claims", "Post-procedure recovery", "Skin quality claims"],
    watchFor: "Big molecules, small studies, and an origin story (human cells, snails, salmon DNA, exosomes) that does the marketing. Applied to intact skin, most of it stays on the surface.",
    summary: "A fast-growing category with a plausible mechanism and a thin, industry-funded evidence base. Exosome products in particular have no approval for any skin use.",
    aliases: ["EGF", "TGF-beta", "human growth factor serum", "PDRN", "polydeoxyribonucleotide", "salmon DNA", "exosome serum", "stem cell serum", "TNS"],
    status: "Cosmetic ingredient",
    forms: ["Serums with recombinant or cell-derived growth factors", "PDRN / polynucleotide creams and serums", "Exosome and 'stem cell' products, usually plant-derived or conditioned media"],
    uses: [
      { use: "Photoaging", grade: "C", note: "A 2023 systematic review found mostly small, short, industry-supported studies with subjective outcomes." },
      { use: "Post-procedure healing", grade: "C", note: "Some split-face data after resurfacing; not standardized." },
      { use: "Exosomes for skin", grade: "Context", note: "No controlled human evidence for topical cosmetic exosomes; FDA has issued consumer alerts about unapproved exosome products." },
    ],
    howToUse: "If used, apply on clean skin before moisturizer; there is no evidence-based schedule.",
    sideEffects: ["Irritation from vehicles", "Unknown long-term effects for cell-derived products"],
    cautions: "Avoid on open wounds unless a clinician directs it; anyone with a history of skin cancer should ask before using growth-factor products on treated areas.",
    access: "Almost always premium-priced.",
    regulatory: "Cosmetic ingredients in the U.S. as long as claims stay cosmetic; injectable PDRN and exosomes are a separate regulatory story covered in the procedures desk.",
    trendNote: "Salmon DNA and exosomes are the 2025–2026 buzzwords; the injectable versions carry the real risk.",
    reviewed: REVIEWED,
    sources: [src.pmGrowthFactors, src.pmCosmeceuticals, src.fdaWrinkle],
    related: { ingredients: ["peptides"], procedures: ["skin-boosters"], trends: ["exosome-skincare", "salmon-dna-pdrn"] },
  },

  // ------------------------------------------------------------------
  // Newer prescriptions people ask about
  // ------------------------------------------------------------------
  {
    slug: "ruxolitinib-cream",
    name: "Ruxolitinib cream",
    family: "Topical JAK inhibitors",
    evidence: "A",
    jobs: ["Vitiligo repigmentation", "Mild to moderate atopic dermatitis"],
    watchFor: "Carries the JAK-inhibitor class boxed warning even though topical absorption is low. Repigmentation takes months and needs continued use.",
    summary: "The first FDA-approved treatment for repigmenting vitiligo and an effective non-steroid eczema cream, priced as a specialty drug.",
    aliases: ["Opzelura", "topical JAK inhibitor", "ruxolitinib for vitiligo"],
    status: "Prescription (U.S.)",
    forms: ["1.5% cream twice daily (Rx, brand only)"],
    uses: [
      { use: "Nonsegmental vitiligo (face and body)", grade: "A", note: "Two phase 3 randomized trials showed substantially more facial repigmentation than vehicle at 24 and 52 weeks." },
      { use: "Mild to moderate atopic dermatitis", grade: "A", note: "Phase 3 trials support itch and clearance benefit versus vehicle." },
    ],
    howToUse: "Thin layer twice daily to affected areas up to 10% of body surface; vitiligo response is judged at 6 months and continues to improve with use.",
    sideEffects: ["Application-site acne or itch", "Nasopharyngitis", "Rare systemic effects reflected in the class warning"],
    cautions: "Class boxed warning on serious infections, cardiovascular events, clots, and malignancy from oral JAK inhibitors; topical absorption is low but the warning applies. Not for use with biologics or other JAK inhibitors.",
    access: "Brand-only with a high list price; coverage often requires prior authorization and failed alternatives.",
    regulatory: "FDA-approved (2021 for atopic dermatitis, 2022 for vitiligo) prescription drug. Approved in the E.U. for vitiligo; availability elsewhere varies.",
    reviewed: REVIEWED,
    sources: [dailymed("ruxolitinib cream", "ruxolitinib cream"), src.pmRuxo, src.aadVitiligo, src.aadAdGuideline],
    related: { ingredients: ["ceramides"] },
  },
  {
    slug: "minoxidil-topical",
    name: "Minoxidil (topical)",
    family: "Hair growth actives",
    evidence: "A",
    jobs: ["Pattern hair loss", "Maintaining density", "Beard and brow use (off-label)"],
    watchFor: "Shedding in the first 4–8 weeks is expected, and stopping reverses the gains. The 5% foam is the standard; oral low-dose minoxidil is a separate prescription trend.",
    summary: "The only OTC drug with decades of evidence for pattern hair loss. Works for many, not all, and only while used.",
    aliases: ["Rogaine", "minoxidil foam", "minoxidil 5%", "minoxidil solution", "oral minoxidil"],
    status: "OTC drug (U.S.)",
    forms: ["2% and 5% solutions and 5% foam (OTC drug)", "Compounded higher strengths and combinations (Rx)", "Oral low-dose tablets (Rx, off-label for hair)"],
    uses: [
      { use: "Androgenetic alopecia", grade: "A", note: "Randomized placebo-controlled trials support increased hair counts; 5% outperforms 2%." },
      { use: "Other hair loss types", grade: "C", note: "Used off-label as an adjunct; evidence is weaker." },
      { use: "Beard or eyebrow growth", grade: "C", note: "Off-label with small studies." },
    ],
    howToUse: "Apply to a dry scalp once (foam) or twice (solution) daily and leave for at least 4 hours; judge at 4–6 months and continue indefinitely.",
    sideEffects: ["Initial shedding", "Scalp irritation (often from propylene glycol in solutions)", "Unwanted facial hair with drips"],
    cautions: "Not recommended in pregnancy or breastfeeding. Keep away from pets, especially cats. Oral minoxidil requires prescriber monitoring for blood pressure and fluid retention.",
    access: "Generic foam and solution are inexpensive; subscription telehealth brands sell the same drug at a markup.",
    regulatory: "FDA-approved OTC drug for hair regrowth; oral minoxidil is approved only for blood pressure and used off-label for hair.",
    trendNote: "Oral minoxidil went viral in 2022–2024; the topical remains the evidence-based starting point.",
    reviewed: REVIEWED,
    sources: [dailymed("minoxidil", "minoxidil"), src.aadHairLoss],
    related: { procedures: ["prp-hair-loss", "hair-transplant"] },
  },
];
