import type { Source, Trend } from "./types";

/**
 * Trend files: what people are doing, what they are told it does, and what
 * the evidence can support. Verdicts are editorial calls; "Avoid" is reserved
 * for documented harm, and "Needs care" means fine for some people with
 * conditions attached.
 */

const REVIEWED = "2026-09-01";

const src = {
  aadTrends: { label: "American Academy of Dermatology — social media skin care trends: dermatologists reveal the facts", url: "https://www.aad.org/news/social-media-skin-care-trends" },
  aadUnsafe: { label: "American Academy of Dermatology — five unsafe skin care trends to avoid", url: "https://www.aad.org/news/5-unsafe-skin-care-trends-to-avoid" },
  aadDermWorld: { label: "AAD DermWorld 2023 — from slugging to snail mucin", url: "https://www.aad.org/dw/monthly/2023/october/feature-from-slugging-to-snail-mucin" },
  aadPetroleum: { label: "American Academy of Dermatology — uses for petroleum jelly", url: "https://www.aad.org/public/everyday-care/skin-care-secrets/routine/petroleum-jelly" },
  aadOrder: { label: "American Academy of Dermatology — applying skin care products in order", url: "https://www.aad.org/public/everyday-care/skin-care-basics/care/apply-skin-care-certain-order" },
  aadRetinoids: { label: "American Academy of Dermatology — retinoid or retinol?", url: "https://www.aad.org/public/everyday-care/skin-care-secrets/anti-aging/retinoid-retinol" },
  aadRedLight: { label: "American Academy of Dermatology — is red light therapy right for your skin?", url: "https://www.aad.org/public/cosmetic/safety/red-light-therapy" },
  aadSunscreenFaq: { label: "American Academy of Dermatology — sunscreen FAQs", url: "https://www.aad.org/public/everyday-care/sun-protection/sunscreen-patients/sunscreen-faqs" },
  aadSunscreenSelect: { label: "American Academy of Dermatology — how to select a sunscreen", url: "https://www.aad.org/public/everyday-care/sun-protection/shade-clothing-sunscreen/how-to-select-sunscreen" },
  aadAcneGuideline: { label: "American Academy of Dermatology — 2024 acne guideline", url: "https://www.aad.org/member/clinical-quality/guidelines/acne" },
  aadDrySkin: { label: "American Academy of Dermatology — tips to relieve dry skin", url: "https://www.aad.org/public/everyday-care/skin-care-basics/dry/dermatologists-tips-relieve-dry-skin" },
  fdaCosmeticsAuthority: { label: "U.S. FDA — how cosmetics are regulated (not FDA approved)", url: "https://www.fda.gov/cosmetics/cosmetics-laws-regulations/fda-authority-over-cosmetics-how-cosmetics-are-not-fda-approved-are-fda-regulated" },
  fdaWellness: { label: "U.S. FDA — general wellness policy for low-risk devices", url: "https://www.fda.gov/regulatory-information/search-fda-guidance-documents/general-wellness-policy-low-risk-devices" },
  fdaExosomes: { label: "U.S. FDA — consumer alert on regenerative medicine products including exosomes", url: "https://www.fda.gov/vaccines-blood-biologics/consumers-biologics/consumer-alert-regenerative-medicine-products-including-stem-cells-and-exosomes" },
  fdaMicroneedling: { label: "U.S. FDA — microneedling devices", url: "https://www.fda.gov/medical-devices/aesthetic-cosmetic-devices/microneedling-devices" },
  fdaNeedleFree: { label: "U.S. FDA — dermal filler do's and don'ts, including the warning against needle-free devices", url: "https://www.fda.gov/consumers/consumer-updates/dermal-filler-dos-and-donts-wrinkles-lips-and-more" },
  fdaSunscreenRulemaking: { label: "U.S. FDA — rulemaking history for OTC sunscreen drug products", url: "https://www.fda.gov/drugs/status-otc-rulemakings/rulemaking-history-otc-sunscreen-drug-products" },
  fdaSkinFacts: { label: "U.S. FDA — Skin Facts: what you need to know about skin lightening products", url: "https://www.fda.gov/consumers/health-fraud-scams/skin-facts-what-you-need-know-about-skin-lightening-products" },
  fdaWrinkle: { label: "U.S. FDA — wrinkle treatments and other anti-aging products", url: "https://www.fda.gov/cosmetics/cosmetic-products/wrinkle-treatments-and-other-anti-aging-products" },
  asps2025: { label: "American Society of Plastic Surgeons — 2025 procedural statistics report (PDF)", url: "https://www.plasticsurgery.org/documents/news/statistics/2025/plastic-surgery-statistics-report-2025.pdf", published: "2025 statistics" },
  pmPetrolatum: { label: "J Allergy Clin Immunol 2016 — petrolatum: barrier repair and antimicrobial responses (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/26431582/" },
  pmSnail: { label: "J Cosmet Dermatol 2024 — snail extract for skin: review of uses, projections, and limitations (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/38429932/" },
  pmBakuchiol: { label: "Br J Dermatol 2019 — bakuchiol versus retinol for photoaging: randomized double-blind trial (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/29947134/" },
  pmCollagen2025: { label: "Am J Med 2025 — collagen supplements and skin aging: meta-analysis of RCTs (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/40324552/" },
  pmCollagen2021: { label: "Int J Dermatol 2021 — hydrolyzed collagen supplementation and skin aging: meta-analysis (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/33742704/" },
  pmLed: { label: "Jagdeo et al., Lasers Surg Med 2018 — LEDs in dermatology: systematic review of RCTs (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/29356026/" },
  pmHomeDevices: { label: "Arch Dermatol Res 2022 — home-based devices in dermatology: systematic review (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/33938981/" },
  pmHomeMultiEnergy: { label: "Lasers Med Sci 2024 — home-use handheld multi-energy device for skin rejuvenation (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/38236440/" },
  pmHocl: { label: "Am J Clin Dermatol 2026 — sodium hypochlorite in dermatology: scoping review (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/41428161/" },
  pmHoclPrep: { label: "Aesthetic Plast Surg 2026 — hypochlorous acid as skin preparation in aesthetic surgery (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/42009924/" },
  pmPdrnTopical: { label: "Molecules 2022 — topical PDRN, vitamin C, and niacinamide mixture on pigmentation and elasticity (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/35209068/" },
  pmGrowthFactors: { label: "J Cosmet Dermatol 2023 — topical growth factor preparations: systematic review (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/37222303/" },
  pmSunscreenAging: { label: "Ann Intern Med 2013 — sunscreen and prevention of skin aging: randomized trial (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/23732711/" },
  pmCosmeceuticals: { label: "Arch Dermatol Res 2024 — cosmeceuticals for anti-aging: systematic review (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/38758222/" },
  pmDelphi: { label: "J Am Acad Dermatol 2025 — skincare ingredients recommended by cosmetic dermatologists: Delphi consensus (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/40233838/" },
  pmMicroneedlingSr: { label: "Dermatol Surg 2020 — microneedling for acne scarring: systematic review (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/31356435/" },
} satisfies Record<string, Source>;

export const trends: Trend[] = [
  {
    slug: "slugging",
    name: "Slugging",
    aliases: ["petroleum jelly at night", "occlusive layer", "Vaseline face"],
    category: "Routine",
    whatItIs: "Finishing a nighttime routine with a thin layer of petrolatum or a petrolatum-based ointment to seal in moisture.",
    claim: "Locks in hydration, repairs the barrier, and wakes you up with 'glass skin'.",
    evidence: "Petrolatum is the best-studied occlusive in dermatology; it cuts water loss sharply and even triggers barrier-repair signaling. The trend simply applies a standard recommendation for dry or irritated skin to everyone, including oily, acne-prone faces, where an all-over occlusive can trap sebum and actives.",
    grade: "A",
    verdict: "Reasonable",
    whoShouldSkip: "Active acne, fungal acne, or very oily skin over the whole face; anyone still adjusting to a new retinoid or acid, which slugging can drive deeper.",
    tryInstead: "Slug selectively: lips, cheeks, hands, heels, and post-procedure skin, over a moisturizer rather than instead of one.",
    reviewed: REVIEWED,
    sources: [src.aadPetroleum, src.aadDermWorld, src.pmPetrolatum],
    related: { ingredients: ["petrolatum", "ceramides"], guides: ["skin-barrier-explained"] },
  },
  {
    slug: "skin-cycling",
    name: "Skin cycling",
    aliases: ["four-night cycle", "exfoliate night retinoid night recovery nights"],
    category: "Routine",
    whatItIs: "A repeating schedule, typically exfoliating acid on night one, retinoid on night two, and two recovery nights of moisturizer only.",
    claim: "Gets the benefits of actives without irritation and 'resets' the barrier.",
    evidence: "There are no trials of the schedule itself. What it encodes, though, is guideline-consistent advice: introduce retinoids gradually, do not stack exfoliants nightly, and moisturize. For many people the recovery nights are the corrective step after the over-exfoliation era; for tolerant skin, nightly retinoid use produces more change.",
    grade: "Context",
    verdict: "Reasonable",
    whoShouldSkip: "People with acne who have been told to use a retinoid nightly; the cycle halves the dose. Anyone using a prescription for a diagnosed condition should follow the prescription, not the trend.",
    tryInstead: "Treat it as a starting scaffold, then move the retinoid toward nightly as tolerated and keep acids to a few nights a week.",
    reviewed: REVIEWED,
    sources: [src.aadRetinoids, src.aadOrder, src.aadAcneGuideline],
    related: { ingredients: ["retinoids", "alpha-hydroxy-acids", "salicylic-acid"], guides: ["retinoid-ladder"] },
  },
  {
    slug: "retinol-sandwiching",
    name: "Retinol sandwiching",
    aliases: ["moisturizer sandwich", "buffering retinoid", "retinoid buffering"],
    category: "Routine",
    whatItIs: "Applying moisturizer, then the retinoid, then moisturizer again to reduce irritation.",
    claim: "Lets you use a retinoid without dryness while keeping the full effect.",
    evidence: "Buffering with moisturizer is a long-standing clinical tolerability strategy; it reduces irritation and may modestly reduce penetration, which is the point during adjustment. No trial has measured whether the sandwich costs efficacy long term. Dermatologists describe it as a fair way to start and a step to drop once tolerated.",
    grade: "Context",
    verdict: "Reasonable",
    whoShouldSkip: "Nobody needs to avoid it; people who tolerate the retinoid already can skip the extra step.",
    tryInstead: "Sandwich for the first month, then apply the retinoid to dry skin and moisturize after.",
    reviewed: REVIEWED,
    sources: [src.aadRetinoids, src.aadOrder],
    related: { ingredients: ["retinoids", "tretinoin", "tazarotene"], guides: ["retinoid-ladder"] },
  },
  {
    slug: "skin-flooding",
    name: "Skin flooding and 'seven-skin' layering",
    aliases: ["skin flooding", "7 skin method", "hydration layering", "damp skin layering"],
    category: "Routine",
    whatItIs: "Layering several watery hydrating products, often hyaluronic acid or toner, on damp skin before a moisturizer.",
    claim: "Deeply hydrates and plumps the skin for a dewy look.",
    evidence: "Humectants on damp skin do raise surface hydration, and a moisturizer on top holds it; that part is basic dermatology. Multiple layers of the same humectant add little over one, and in dry air unsealed humectants can pull water outward. The effect is real, surface-level, and temporary.",
    grade: "B",
    verdict: "Harmless, low value",
    whoShouldSkip: "People with reactive skin adding several fragranced products at once; each layer is another exposure.",
    tryInstead: "One humectant on damp skin, then a moisturizer, then (if dry) an occlusive. Three steps deliver what seven promise.",
    reviewed: REVIEWED,
    sources: [src.aadDrySkin, src.aadOrder, src.aadDermWorld],
    related: { ingredients: ["hyaluronic-acid", "ceramides", "petrolatum"] },
  },
  {
    slug: "glass-skin",
    name: "Glass skin",
    aliases: ["glass skin routine", "dewy skin", "K-beauty glow"],
    category: "Routine",
    whatItIs: "A Korean-beauty ideal of poreless, luminous skin pursued through multi-step hydration, gentle exfoliation, and sun protection.",
    claim: "Anyone can reach a flawless, reflective finish with the right routine.",
    evidence: "The routine pieces that work are unremarkable: consistent sun protection, hydration, and not over-exfoliating. The finish in photos is also lighting, filters, makeup, and skin type. Dermatologists interviewed by the AAD describe the healthy-skin goal as reasonable and the flawless standard as unattainable for most.",
    grade: "Context",
    verdict: "Harmless, low value",
    whoShouldSkip: "People with acne, rosacea, or eczema chasing a texture their condition will not produce; the goal can drive overuse of products.",
    tryInstead: "Sunscreen, a gentle routine, and treatment for the actual condition; skip the ten-step count.",
    reviewed: REVIEWED,
    sources: [src.aadTrends, src.aadSunscreenFaq],
    related: { ingredients: ["sunscreen", "hyaluronic-acid", "niacinamide"], guides: ["routine-from-zero"] },
  },
  {
    slug: "beef-tallow",
    name: "Beef tallow as moisturizer",
    aliases: ["tallow balm", "whipped tallow", "grass-fed tallow skincare"],
    category: "Ingredient",
    whatItIs: "Rendered beef fat, sometimes whipped with oils, applied as a face or body moisturizer and marketed as 'ancestral' or 'natural'.",
    claim: "Matches the skin's own lipids, heals acne and eczema, and beats 'chemical' moisturizers.",
    evidence: "We found no controlled human trials of tallow as a skin moisturizer. It is an occlusive, saturated fat that will reduce water loss like other heavy emollients, with a higher chance of clogging pores and an unregulated supply chain. Rancidity and contamination are the practical risks with home or small-batch products.",
    grade: "Context",
    verdict: "Needs care",
    whoShouldSkip: "Acne-prone skin, rosacea, and anyone relying on it to treat eczema instead of proven therapy.",
    tryInstead: "Petrolatum or a ceramide moisturizer does the occlusive job with trial data and no rancidity problem.",
    reviewed: REVIEWED,
    sources: [src.aadTrends, src.aadPetroleum, src.fdaCosmeticsAuthority],
    related: { ingredients: ["petrolatum", "ceramides"], trends: ["slugging"] },
  },
  {
    slug: "snail-mucin",
    name: "Snail mucin",
    aliases: ["snail secretion filtrate", "snail essence", "COSRX snail"],
    category: "Ingredient",
    whatItIs: "Filtered secretion from farmed snails used in serums and essences, popular through Korean skincare.",
    claim: "Hydrates, heals, fades scars, and repairs the barrier.",
    evidence: "A 2024 review found mostly small, short, manufacturer-linked studies and wound-healing data in animals; the human cosmetic evidence supports hydration and comfort, not scar repair. The filtrate is largely humectants and glycoproteins, so a pleasant hydrating texture is the honest expectation.",
    grade: "C",
    verdict: "Harmless, low value",
    whoShouldSkip: "People with shellfish or mollusk allergies should patch test; vegans by preference.",
    tryInstead: "Any well-formulated humectant serum does the same job for less mystique.",
    reviewed: REVIEWED,
    sources: [src.pmSnail, src.aadDermWorld],
    related: { ingredients: ["hyaluronic-acid", "niacinamide"] },
  },
  {
    slug: "hypochlorous-acid-spray",
    name: "Hypochlorous acid spray",
    aliases: ["HOCl spray", "hypochlorous mist", "Tower 28 SOS", "post-workout spray"],
    category: "Ingredient",
    whatItIs: "A dilute, skin-friendly form of the chlorine chemistry used in wound cleansers, sold as a face mist for redness, acne, and 'resetting' skin after sweat.",
    claim: "Kills acne bacteria, calms eczema and rosacea, and replaces cleansing on the go.",
    evidence: "Hypochlorous solutions are well established as wound and skin antiseptics and are used in surgical skin prep with good tolerability. Controlled trials of consumer mists for acne, eczema, or rosacea are scarce; the plausible benefit is mild antimicrobial and soothing action on a clean surface. It does not remove sunscreen, oil, or makeup.",
    grade: "C",
    verdict: "Harmless, low value",
    whoShouldSkip: "Nobody in particular; it is not a substitute for prescribed treatment of eczema, acne, or rosacea.",
    tryInstead: "Keep it as a comfort mist or post-workout rinse; treat the condition with evidence-based actives.",
    reviewed: REVIEWED,
    sources: [src.pmHocl, src.pmHoclPrep],
    related: { ingredients: ["azelaic-acid", "benzoyl-peroxide"] },
  },
  {
    slug: "home-led-masks",
    name: "At-home LED masks",
    aliases: ["red light mask", "LED face mask", "blue light mask", "Omnilux", "CurrentBody"],
    category: "Device",
    whatItIs: "Wearable panels of red, near-infrared, or blue LEDs used for minutes a day at home, priced from under $100 to over $1,000.",
    claim: "Builds collagen, clears acne, and rivals in-office treatment.",
    evidence: "The randomized-trial base for LEDs shows small, inconsistent benefits for acne and photoaging with professional-strength devices; home masks are weaker and mostly cleared for modest claims or sold as wellness products with no effectiveness review. The AAD notes some FDA-cleared devices exist, that they are less powerful than clinic devices, and that no one can predict who will respond.",
    grade: "C",
    verdict: "Needs care",
    whoShouldSkip: "Photosensitive conditions such as lupus, photosensitizing medication, and anyone treating skin cancer or precancer in the area; eye protection is required.",
    tryInstead: "If buying, choose a device with a stated wavelength and irradiance and an FDA clearance for the claim you care about, and set a 12-week check-in.",
    reviewed: REVIEWED,
    sources: [src.aadRedLight, src.pmLed, src.pmHomeDevices, src.fdaWellness],
    related: { procedures: ["led-light-therapy", "photodynamic-therapy"] },
  },
  {
    slug: "microcurrent-devices",
    name: "Microcurrent facial devices",
    aliases: ["NuFace", "microcurrent lifting", "facial toning device", "ZIIP"],
    category: "Device",
    whatItIs: "Handheld devices that pass low-level electrical current through the face, marketed as a 'workout' for facial muscles.",
    claim: "Lifts, tones, and sculpts the face with cumulative use.",
    evidence: "Evidence is limited to small, mostly manufacturer-sponsored studies with subjective or short-term outcomes; systematic reviews of home devices rate the effect uncertain. Any lift is transient swelling and muscle stimulation that fades within hours to days.",
    grade: "C",
    verdict: "Harmless, low value",
    whoShouldSkip: "Pacemakers or implanted electronics, epilepsy, pregnancy, and active facial infection or recent filler per device labeling.",
    tryInstead: "For lasting lift, the procedures desk compares energy devices and surgery honestly; for a temporary event-day effect, the device is harmless.",
    reviewed: REVIEWED,
    sources: [src.pmHomeDevices, src.pmHomeMultiEnergy, src.fdaWellness],
    related: { procedures: ["rf-tightening", "ultrasound-tightening"] },
  },
  {
    slug: "collagen-supplements",
    name: "Collagen supplements",
    aliases: ["collagen peptides", "hydrolyzed collagen", "marine collagen", "collagen powder"],
    category: "Supplement",
    whatItIs: "Oral hydrolyzed collagen powders, capsules, and drinks taken daily for skin.",
    claim: "Rebuilds skin collagen, reduces wrinkles, and improves elasticity from the inside.",
    evidence: "Meta-analyses of randomized trials report small improvements in measured hydration and elasticity over 8–12 weeks, but most trials are short, industry-funded, and use instrument outcomes rather than visible change; a 2025 analysis of higher-quality trials found the effect shrinks when industry trials are excluded. Supplements are not reviewed by FDA for effectiveness before sale.",
    grade: "C",
    verdict: "Harmless, low value",
    whoShouldSkip: "Anyone with fish or shellfish allergy using marine collagen; people spending on it instead of sunscreen and a retinoid.",
    tryInstead: "Sunscreen and a retinoid have randomized evidence for the same goal; keep collagen if you like it, but expect little.",
    reviewed: REVIEWED,
    sources: [src.pmCollagen2025, src.pmCollagen2021, src.pmCosmeceuticals],
    related: { ingredients: ["sunscreen", "retinoids"] },
  },
  {
    slug: "skinimalism",
    name: "Skinimalism (minimal routines)",
    aliases: ["skin minimalism", "three-step routine", "less is more skincare"],
    category: "Routine",
    whatItIs: "Cutting routines to a cleanser, a moisturizer, sunscreen, and at most one or two evidence-based actives.",
    claim: "Fewer products means healthier skin and less irritation.",
    evidence: "Dermatology guidance has long favored simple routines built around sunscreen, a moisturizer, and a retinoid, and a 2025 Delphi consensus of cosmetic dermatologists converges on the same short list of ingredients. Fewer products reduce irritant and allergen exposure. The limit is that a diagnosed condition may still need prescription treatment.",
    grade: "B",
    verdict: "Reasonable",
    whoShouldSkip: "Nobody; people with acne, rosacea, melasma, or eczema should include the prescribed treatment in their short list.",
    tryInstead: "Cleanser, moisturizer, sunscreen, plus a retinoid at night; add one targeted active only for a specific concern.",
    reviewed: REVIEWED,
    sources: [src.pmDelphi, src.aadOrder, src.aadSunscreenFaq],
    related: { guides: ["routine-from-zero"], ingredients: ["sunscreen", "retinoids", "niacinamide"] },
  },
  {
    slug: "sunscreen-contouring",
    name: "Sunscreen contouring",
    aliases: ["SPF contouring", "tan lines contour", "strategic sunscreen"],
    category: "Safety",
    whatItIs: "Applying sunscreen only to high points of the face so the sun 'contours' the rest.",
    claim: "A natural, free contour without bronzer.",
    evidence: "It is deliberate, uneven UV damage. Sun exposure without protection raises skin cancer risk and drives the pigment and wrinkle changes the sunscreen trials prevent. Uneven application also produces patchy pigmentation that is harder to treat than a tan.",
    grade: "A",
    verdict: "Avoid",
    whoShouldSkip: "Everyone; especially anyone with melasma, a history of skin cancer, or a family history of melanoma.",
    tryInstead: "Full-face sunscreen and a bronzer.",
    reviewed: REVIEWED,
    sources: [src.aadUnsafe, src.aadSunscreenFaq, src.pmSunscreenAging],
    related: { ingredients: ["sunscreen"] },
  },
  {
    slug: "diy-procedures",
    name: "DIY needling, peels, and injections",
    aliases: ["at-home microneedling", "dermaroller", "DIY chemical peel", "hyaluron pen", "at-home filler"],
    category: "Safety",
    whatItIs: "Home use of dermarollers, high-strength acids bought online, and needle-free 'hyaluron pens' or imported injectables.",
    claim: "Professional results at home for a fraction of the cost.",
    evidence: "FDA has not cleared microneedling devices for home use at treatment depths, has warned against needle-free filler devices, and has documented burns from online peels and infections from unlicensed injections. Rollers reused at home breach the skin without sterility; peels sold at professional strengths lack the neutralization and skin-tone judgment that keep them safe.",
    grade: "A",
    verdict: "Avoid",
    whoShouldSkip: "Everyone; the risk is infection, scarring, permanent pigment change, and, for injections, vascular injury.",
    tryInstead: "Adapalene, a retinoid, or a cosmetic-strength acid at home; needling, peels, and injections in a medical setting.",
    reviewed: REVIEWED,
    sources: [src.aadUnsafe, src.fdaNeedleFree, src.fdaMicroneedling, src.pmMicroneedlingSr],
    related: { procedures: ["microneedling", "superficial-chemical-peel", "hyaluronic-acid-fillers"], guides: ["procedure-safety-checklist"] },
  },
  {
    slug: "nasal-tanning-spray",
    name: "Nasal tanning sprays and 'tanning peptides'",
    aliases: ["Melanotan", "melanotan II", "tanning nasal spray", "tanning injections"],
    category: "Safety",
    whatItIs: "Unapproved synthetic melanocortin peptides sold online as nasal sprays or injections to darken skin.",
    claim: "A deep tan with less sun.",
    evidence: "These products are not approved anywhere for tanning, are sold without quality control, and have been linked in case reports to nausea, new or changing moles, and melanoma concerns. The AAD lists them among the trends to avoid outright.",
    grade: "A",
    verdict: "Avoid",
    whoShouldSkip: "Everyone.",
    tryInstead: "Self-tanner with dihydroxyacetone for color; sunscreen for skin.",
    reviewed: REVIEWED,
    sources: [src.aadUnsafe, src.fdaCosmeticsAuthority],
    related: { ingredients: ["sunscreen"] },
  },
  {
    slug: "salmon-dna-pdrn",
    name: "Salmon DNA (PDRN) skincare",
    aliases: ["PDRN serum", "polynucleotide serum", "salmon sperm facial", "Rejuran topical"],
    category: "Ingredient",
    whatItIs: "Polydeoxyribonucleotide fragments derived from salmon, sold in topical serums and marketed alongside the injectable versions used abroad.",
    claim: "Regenerates skin, repairs damage, and delivers injectable-level results from a serum.",
    evidence: "Topical studies are small and mostly mechanistic or combined with other actives, with no independent randomized trial showing durable change from PDRN on intact skin; the molecule is large and poorly absorbed. The injectable versions have their own early evidence and are not FDA approved in the U.S.",
    grade: "C",
    verdict: "Harmless, low value",
    whoShouldSkip: "Fish allergy warrants a patch test; anyone expecting injectable results from a serum.",
    tryInstead: "A retinoid and sunscreen for repair; the procedures desk covers what injectable polynucleotides can and cannot claim.",
    reviewed: REVIEWED,
    sources: [src.pmPdrnTopical, src.pmGrowthFactors, src.fdaWrinkle],
    related: { ingredients: ["growth-factors"], procedures: ["skin-boosters"] },
  },
  {
    slug: "exosome-skincare",
    name: "Exosome skincare",
    aliases: ["exosome serum", "stem cell exosomes", "exosome facial", "plant exosomes"],
    category: "Ingredient",
    whatItIs: "Products claiming to contain extracellular vesicles from human, animal, or plant cells, sold as serums and as post-procedure add-ons.",
    claim: "Cell-to-cell messengers that regenerate skin and speed healing.",
    evidence: "No controlled human evidence supports topical cosmetic exosomes, most products cannot demonstrate what they contain or whether it survives formulation, and FDA has issued consumer alerts about unapproved exosome products. Post-procedure application on open skin raises contamination and immune questions that the marketing does not address.",
    grade: "Context",
    verdict: "Needs care",
    whoShouldSkip: "Anyone with freshly needled or lasered skin being offered an exosome 'boost'; anyone paying a premium for a serum.",
    tryInstead: "Petrolatum and a bland moisturizer after procedures, per standard aftercare.",
    reviewed: REVIEWED,
    sources: [src.fdaExosomes, src.pmGrowthFactors, src.fdaWrinkle],
    related: { ingredients: ["growth-factors", "petrolatum"], procedures: ["skin-boosters", "microneedling"] },
  },
  {
    slug: "korean-sunscreen-imports",
    name: "Imported Korean and European sunscreens",
    aliases: ["K-beauty sunscreen", "Beauty of Joseon sunscreen", "European sunscreen filters", "Tinosorb", "Uvinul"],
    category: "Ingredient",
    whatItIs: "Buying sunscreens formulated with UV filters approved in Asia or Europe but not yet in the U.S., often through marketplaces or travel.",
    claim: "Better protection and nicer textures than American sunscreens.",
    evidence: "The filters are real and well studied abroad, and their textures drive daily use, which is what protects skin. The catch is regulatory: products sold outside FDA's OTC framework can be counterfeit or relabeled, and U.S. labeling rules (SPF testing, broad-spectrum claims) do not apply. Bemotrizinol's 2026 U.S. permission is the first step toward closing the gap.",
    grade: "B",
    verdict: "Needs care",
    whoShouldSkip: "Anyone buying from unverified resellers; counterfeit sunscreen is a documented problem.",
    tryInstead: "Buy from the brand or an authorized retailer, check for tampering, and use it daily; any sunscreen you apply beats a superior one you skip.",
    reviewed: REVIEWED,
    sources: [src.fdaSunscreenRulemaking, src.aadSunscreenSelect, src.aadSunscreenFaq],
    related: { ingredients: ["sunscreen", "bemotrizinol"], dispatches: ["bemotrizinol-us-sunscreen-filter"] },
  },
  {
    slug: "glp1-face",
    name: "'Ozempic face' and post-weight-loss skin",
    aliases: ["Ozempic face", "GLP-1 face", "semaglutide face", "weight loss facial volume"],
    category: "Procedure",
    whatItIs: "Facial volume loss and laxity after rapid weight loss on GLP-1 medications, and the surge of treatments marketed to fix it.",
    claim: "Fillers, biostimulators, or surgery can restore the face after weight loss.",
    evidence: "The change is fat loss and skin laxity, not a drug side effect on skin itself; it follows any rapid weight loss. ASPS's 2025 report documents rising facelift, neck lift, and fat-grafting volumes it links to GLP-1 patients. Fillers and biostimulators address volume; significant laxity needs surgery, and stability of weight matters before either.",
    grade: "B",
    verdict: "Needs care",
    whoShouldSkip: "Anyone still losing weight or with an unstable dose; results shift as the face changes.",
    tryInstead: "Wait for weight stability, then compare fat grafting, fillers, and lifting in the procedures desk with a surgeon who has seen post-GLP-1 faces.",
    reviewed: REVIEWED,
    sources: [src.asps2025],
    related: { procedures: ["hyaluronic-acid-fillers", "biostimulator-fillers", "facelift-neck-lift"] },
  },
  {
    slug: "bakuchiol-natural-retinol",
    name: "Bakuchiol as 'natural retinol'",
    aliases: ["bakuchiol serum", "plant retinol", "retinol alternative"],
    category: "Ingredient",
    whatItIs: "A plant-derived compound marketed as a gentler, pregnancy-friendly retinol substitute.",
    claim: "Retinol results without irritation or pregnancy concerns.",
    evidence: "One randomized double-blind trial found bakuchiol 0.5% twice daily comparable to retinol 0.5% nightly for photoaging over 12 weeks, with less scaling. It is one trial, against cosmetic retinol rather than a prescription retinoid, and pregnancy safety has not been formally studied; 'not a retinoid' is not the same as 'tested in pregnancy'.",
    grade: "C",
    verdict: "Reasonable",
    whoShouldSkip: "Anyone expecting tretinoin-level results; pregnant people should ask a clinician rather than assume safety from marketing.",
    tryInstead: "Fine as a gentle option; a retinoid remains the evidence-based choice when tolerated and not pregnant.",
    reviewed: REVIEWED,
    sources: [src.pmBakuchiol, src.aadRetinoids],
    related: { ingredients: ["retinol-retinal", "retinoids"] },
  },
];
